### ISSUE TITLE
Fix App Image build issues in OpenShift

### ISSUE THREAD

**Issue by davidclaveau** [bcgov/lucy-web#1167]
**Describe the task**
Fix an issue with LUCY to deployment of the Web App to OpenShift

**Acceptance Criteria**
- [ ] Build the invasivesbc-app image in OpenShift
- [ ] Succesfully deploys the app to DEV

**Additional context**
- The GitHub action currently fails when attempting to build the App image in OpenShift, citing issues with the Angular version
- <img width="1582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEREQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b1cd877b06e3324ca0aecc35bc44ebf63cf3716/Screenshot%202024-01-12%20at%202.20.49%E2%80%AFPM.png" alt="Screenshot 2024-01-12 at 2.20.49 PM.png" />

**Comment by LocalNewsTV** [comment]
This work may not be completed if we are able to integrate keycloak permissions into the application instead, rendering this application unneeded

**Comment by davidclaveau** [comment]
Keycloak ticket: [INSPECT 281](https://github.com/bcgov/invasivesBC-mussels-iOS/issues/281)
