### ISSUE TITLE
Turn on/off map layers from the data warehouse 

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#262]
**As a** *InvasivesBC Web App User* **I want** *to turn on and off relevant map layers on our map in the application* **So That** *to specify the context which I can see on the map and ensure only the details I need are displayed*

**Acceptance Criteria**
- [x] Given I am creating an observation or treatment, When I look at the map, Then the map layers are on by default
- [x] Given I am Creating an observation or treatment, When I turn on/off the Regional districts layer, Then only the regional districts are removed or added to the map
- [x] Given I am Creating an observation or treatment, When I turn on/off the Municipalities layer, Then only the Municipalities are removed or added to the map
- [x] Given I am Creating an observation or treatment, When I turn on/off the Wells layer, Then only the Wells are removed or added to the map

**Comment by mikeshasko** [comment]
Functionality good / correct.

- The blue / red text change on the toggle is good is ambiguous as to the on state.... perhaps the off state is a grey text and on is bolded colour
- The yellow well symbol impossible to see against the leaflet based map.
