### ISSUE TITLE
Select multiple observations on a Mechanical Treatment

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#267]
**As a** *InvasivesBC Web App user* **I want** *to select multiple observations when creating a mechanical treatment record* **So That** *all of the species I mechanically treated in a treatment area*

**Additional Context**
- How do we establish the "select" of multiples.
- not required - _Mike to supply test data from IAPP before it can be ready to go_
- Specific fields to transfer to the other selected treatments
- Future enhancement - confine the list or selection to some distance value.

**Acceptance Criteria**
- [x] Given I am creating a mechanical treatment record, when I select an observation it is displayed as selected and the list remains visible for additional selections. 
- [x] Remove the "species" header text
- [x] Remove the Species title and field dropdown

**Comment by fwpushan** [comment]
Tests:
As a user, I can select multiple Observations while creating Mechanical treatment.
As a user, I can remove any selected observation while updating  Mechanical treatment.
As a user, I can view multiple selected observations while viewing Mechanical treatment.

NB. The Species field is removed from Mechanical treatment
All Test Passed
