### ISSUE TITLE
Basic Search

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#268]
**As a** *InvasivesBC Web App User* **I want** *basic search on Observation ID, Observer Name, Species, Jurisdiction, or Agency * **So That** *I can view any associated observations with the given single search variable*

**Additional Context**
- we only want to search the 5 mentioned variables
- returns any matching text string from those variables
- search returns the values matching the variables as a substring
- case insensitive

**Acceptance Criteria**
- [x] Given I type Mike into the basic search, When I hit enter, Then the search results include all records with Mike in one of the 5 mentioned variables
- [x] Given I perform a search, When I view the results, Then they are displayed in reverse chronological order based on when they were last updated
- [x] Given I perform a search for "Mike", when I view the results I should see any record with mike included
- [x] Given I perform a search, when I look at the results, then the results are paginated with a maximum of 10 records per page

**Comment by rajfreshworks** [comment]
Apart from the AC, the following works are also done in this ticket

- Updated the material table UI to match the designs
- Removed the `test` expansion panel

**Comment by fwpushan** [comment]
Search is successful with 
1. Observer name
2. Species 
3. Jurisdiction 
4. Id 
5. Agency 

Ordering is also fine.

**Comment by mikeshasko** [comment]
@fwpushan  

Trying to test this ... creating observations under istest2 and I'm getting a submission error 401

**Comment by fwpushan** [comment]
istest2 don't have write access to our regular database.
