### ISSUE TITLE
Capture geometry (point) to support the creation of an observation/treatment of a mobile device

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#282]
**As a** *InvasiveBC Ipad App user* **I want** to be able to capture an observation with point geometry directly from the GPS of a mobile device and have that geometry reflected as in the observation/treatment record. 

**Geometry Additional Context**
- _This is the 1st of 4 types of collection methods to be made available in the mobile field collection application_
- An initial anchor point provided by GPS is required for the observation
- The user is required to enter a radius (in meters) at that point to a (minimum 1.0 meters to a maximum radius of 20.0 meters (decimeter precision)
- A circle is generated about that point and an area calculated
- the resulting anchor point and circle appear on the map
- the anchor point should be displayed as a red + and the circle as a thin red solid line.

**Observation Additional Context**
- adopt the same database elements from the web version
- design the input to present as a very compact modal with toggles / drop downs
- design the collection of the geometry first and once confirmed display the input modal
- allow the same confirmation / QC components prior to confirm

**Acceptance Criteria**

- [ ] Given the anchor point, When confirmed, Then the user is prompted to type in a radius
- [ ] The anchor point and circle are draw accordingly. The user can accept or type in a new radius.
- [ ] Given a selection to add a point feature, When the selection is made, Then the user is prompted to accept an anchor point from the current device location and/or hit the save button.
- [ ] Once saved, the user moves on to create obs or treatment

**Comment by ZoeSimon** [comment]
@AmirShayegh Can you point us to the repo and which of the above items are done?

**Comment by ghost** [comment]
![Geometry_CreatePoint.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/65f4bbf2-7d09-48ab-9ade-551e300c0ec6)

**Comment by ZoeSimon** [comment]
@victorchong Have a look at this one
