### ISSUE TITLE
Capture geometry (box) to support the creation of an observation/treatment of a mobile device

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#283]
As a general user I want to be able to capture a geometry type (specifically a box location) directly from the GPS of a mobile device and have that geometry reflected as in the observation/treatment record.

**Additional Context**

- This is the 2nd of 4 types of collection methods to be made available in the mobile field collection application
- An initial anchor point for the observation is required
- The user is required to enter a height (in meters) and width of the area surrounding the anchor point
- The minimum value is 1.0 meters to a maximum of 20.0 meters
- A box is generated about that point and an area calculated
- the resulting anchor point and box appear on the map
- the number of vertices used to record and draw the box is 4 points (automatically determined)
- the anchor point should be displayed as a red + and the box as a thin red solid line.

**Acceptance Criteria**
- [ ] Given a selection to add a point feature, When the selection is made, Then the user is prompted to accept an anchor point from the current device location
- [ ] Given the anchor point, When confirmed, Then the user is prompted to type in a width and height value
- [ ] The anchor point and box are draw accordingly. The user can accept or re-type in a new values.

Note on operations ... If it is deemed easier to simply define a length/width set of lines, or a diagonal then fit a box - that would be fine. The anchor point then automatically becomes the center.

**Comment by ghost** [comment]
![Geometry_CreateBox.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/4d49ee50-c9d9-41fc-af4a-e52716b48e52)
