### ISSUE TITLE
Capture geometry (waypoint) to support the creation of an observation/treatment of a mobile device

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#284]
As a general user I want to be able to capture a geometry type (specifically a waypoint path) directly from the GPS of a mobile device and have that geometry reflected as in the observation/treatment record.

**Additional Context**

- This is the 3rd of 4 types of collection methods to be made available in the mobile field collection application
- An initial anchor point for the observation is required
- The user is required to enter a sequence of points from the anchor along a linear path.
- The minimum number of points is 2 (the anchor plus 1) up to 20 total points.
- As each point is captured, the distance to the previous point should be greater than 1 meter for that point to be retained
- The user is prompted to enter an offset distance that provides width to the path. 
- Minimum of 1 meter to a maximum of 10 meters.
- A polygon is generated about that waypoint path using that offset to both sides of the path and an area calculated
- the resulting anchor point and polygon appear on the map. The user can accept or reject the geometry (no edit)

**Acceptance Criteria**
- [ ] Given a selection to add a point feature, When the selection is made, Then the user is prompted to accept an anchor point from the current device location
- [ ] Given the anchor point, When confirmed, Then the user is prompted to record the waypoints vai on screen capture or stylus
- [ ] The anchor point and polygon are draw accordingly. The user can accept or re-type in a new offset value.
- [ ] Rather than allowing the edit of individual points, the user and reject the waypoint sequence and re-do it.

**Comment by ghost** [comment]
![Geometry_CreateWaypoint.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/993edd96-4402-42e8-9900-5da860f53049)
