### ISSUE TITLE
Capture geometry (polygon) to support the creation of an observation/treatment of a mobile device

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#285]
As a general user I want to be able to capture a geometry type (specifically a polygon) directly from the GPS of a mobile device and have that geometry reflected as in the observation/treatment record.

**Additional Context**
- This is the 4th of 4 types of collection methods to be made available in the mobile field collection application
- An initial anchor point for the observation is required  ** This is the start and end point of the enclosed shape. It is also the point coordinates used / displayed in the form lat/long AND used as the marker location on the map **
- The user is required to define a polygon using a stylus.
- **3 points is the minimum number of points to make a poly (in this case a triangle).**
- **The minimum area value is 1.0 sq meters (a 1m by 1m poly) to a maximum of 10000 sq meters (ie a hectare)**
- The anchor point would be the start/end point of the polygon 
- The minimum vertex distance is to be 1.0 meters.
- The number of vertices used to record and draw the polygon should be capped at 20 points **This was a Web constraint ... the mobile GeoJSon probably has no upper boundary. We want to avoid the user creating a highly convoluted shape so and a limit of 20 will constrain their complexity.**

**Acceptance Criteria**
- [ ] Given a selection to add a point feature, When the selection is made, the user is prompted to accept an anchor point from the current device location
- [ ] Given the anchor point, When confirmed, Then the user is prompted to define the polygon
- [ ] The anchor point and polygon are draw accordingly. The user can accept or re-draw the polygon (no edit)
- [ ] Include the dialog box (as per mock up) at the top of the form.

**Comment by ghost** [comment]
![Geometry_CreatePolygon.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/349e662b-b68f-4978-b6d1-acb01d673d3a)

**Comment by victorc-bcgov** [comment]
As discussed in #752 , we should bring in the guidance text from the previous screen, i.e. "Define 3 or more points along your boundary edge then return to your start point to close the polygon." This instruction seems incongruent with "Enter a linear path and double click at the end point", however, which asks the user to double-click on the final point to close the polygon.

I prefer the "double click" method as I think it would be easier to implement and use (i.e. detect action double-click and automatically close polygon vs. detect location of last point and decide if it is close-enough to the initial point).

**Comment by anissa-agahchen** [comment]
@victorchong @mikeshasko 
* The instruction is brought in 
* Currently, the polygon is created as points are added .... maybe a demo can help show what is currently being done and what can be done differently
* as for double-clicking ... we'll need to ask Shasko to test on the ipad once we get there ... not sure how it would work on a device at the moment

**Comment by victorc-bcgov** [comment]
From a UX perspective, I like the auto-polygon creation better than the other two solutions previously mentioned. Looking forward to seeing a quick demo. :-) Once the solution is adopted, we will need to update the guidance text to match.

**Comment by ghost** [comment]
The text on this response to the user is incorrect x2.
Can it just say the "The maximum area has exceeded 10,000 sq metres (1 hectare)."
The threshold is 10,000 sq m.

![IMG_0075.PNG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/fd3f0db8-4928-465c-871e-bde362d76b9d)

**Comment by ghost** [comment]
This condition can arise. Probably not much we can do about it.

![IMG_0076.PNG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/f5232278-ae78-4923-bfd9-4ef16996c211)

**Comment by anissa-agahchen** [comment]
TODO:

* round latitude to 6 decimal places
* round longitude to 6 decimal places
* round area to 1 decimal place

**Comment by anissa-agahchen** [comment]
All above completed, closing the ticket
