### ISSUE TITLE
Extraction of warehouse layer attributes into the observation database

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#286]
As a Data Entry+ user when I complete an observation I want the system to infer data warehouse attributes based on the anchor location. 

**Additional Context**
- Related to #261
- From issue 261 3 data layers are to be referenced: wells (points), Municipalities, Regional Districts.
- The layer name and attribute fields as described in the comments below.
- The default state for these variables can be "pending", not <null> as connections to the warehouse may be an issue at any time. 
-  In many cases an anchor location may not fall in any warehouse layer reference polygon. If this is the case the attributes get assigned "unassigned"

**Acceptance Criteria**
- [ ] Once an anchor point has been confirmed with any activity, the system returns the attribute data from the layer-based query (outgoing) into the Invasive record.
- [ ] Web: Wells
- [ ] Web: Municipalites
- [ ] Web: Regional Districts

Ask Andrea for an estimate.

**Comment by mikeshasko** [comment]
Municipal layer:  WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_MUNICIPALITIES_SP

Attributes:  
ADMIN_AREA_NAME  ie "Cariboo Regional District"
ADMIN_AREA_ABBREVIATION  ie "CRD"

![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/bfc1ddf7-3232-4263-b969-046eb960a46a)

**Comment by mikeshasko** [comment]
Municipal layer: WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_MUNICIPALITIES_SP

Attributes:
ADMIN_AREA_NAME ie "City of Kamloops"
ADMIN_AREA_ABBREVIATION ie "Kamloops"


![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/0b4a21d7-52d9-47c5-9564-687ad43b48ab)

**Comment by jakemorr** [comment]
@mikeshasko we will want to have a seperateticket for mobile and for Web. having them combined in 1 makes it very big
