### ISSUE TITLE
Add OWASP Zap to Pipeline

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#294]
**Describe the task**
we need to add Zap to our pipeline as an automated security test. 

**Acceptance criteria:**
- [ ] Pipeline deployment works with Zap
- [x] contact other teams to see how they have implemented OWASP Zap
- [ ] add Tickets for any sfailures found by OWASP Zap

**Comment by thegentlemanphysicist** [comment]
Jon's summary of what he tried:

1. Unlike many projects in the lab, the sonar scanner is not run through a Jenkins step, but through an npm package. This meant the dev hub documentation was or very limited use.
2. After conversations with Shelly she recommended installing Sonnar scanner from scratch in a way more inline with other projects.  i.e. as a build step in the pipeline.
3.  *Before* doing this I would recommend giving some time to attempting to update the existing sonar scanner for ZAP by looking at this sonar qube image being used.
4.  Lastly and this may be outside the scope of this ticket, but we should look into integrating the sonarscanner results with the sonar qube servers.  I believe it is possible to set up a na account on one of the existing sonnar cube servers if we need easy access to the code quality reports.
