### ISSUE TITLE
Create record with Waypoint Geometry

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#295]
As any user, I want to be able to define an observation by defining a path (with a width) that captures the observation along a linear corridor so that observations and treatment observations that occur along roads/rivers can be properly defined spatially.

 [REQ 018]

**Acceptance criteria:**
- [x] minimum of 2 points required
- [x] maximum of **20** points 
- [x] requires a width in meters  -total meters along the path sum of both sides
- [ ] the process correctly process the test data (attached) 
- [ ] the process correctly process the 2 "error" paths (attached)
- [x]   change maximum 20m between 2 points to **200m**
- [x] minimum 1m between 2 points
- [x]   change maximum 200m long to **2000m**
- [x] Points must be sequential
- [x] The interface must allow the user to enter points and have the map display those points.
- [x] Upon completion, the user clicks to proceed and the buffer is created and displayed.

**Additional Context**
- Mock up: https://invis.io/RTV1FSJSP62
- The WayPoint_Code.txt algorith provided creates a corridor along a user-provided path.
- Several test case files are attached.
![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/99b94f48-1244-482b-aabc-dbcc0ffdce3a)
- Additional content including CSVs for testing in Jira: https://apps.nrs.gov.bc.ca/int/jira/browse/INS-876

**Comment by fwpushan** [comment]
The main functionality is working fine. Few minor issues are there but not blocking the user to use this functionality.
