### ISSUE TITLE
Report a Bug - Inspect

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#296]
**As a** *user of the inspect application* **I want** *to report when something unexpected occurs with the application* **So That** *it may be improved and/or avoided in the future*

**Acceptance Criteria:**
- [x] given a bug is found by a when i press the report bug button then a modal opens with some prepopulated information and it is sent to the API
- [x] given a bug is found by a user when they report a bug then an email is sent to/received by Mike Shasko

Additional Context:
- [ ] reach out to common services to understand their emailing service

**Comment by jakemorr** [comment]
"Cool! The best way to reach out would probably be to join the #nr-common-services-showcase channel and then anyone on the team can help out. We also have our catalogue site which has some information on our services: https://bcgov.github.io/common-service-showcase/. We're in the progress of revamping both our onboarding process and the website but those won't be ready for another sprint or two each" from Common services Scrum MAster

**Comment by mikeshasko** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/f27e9dcb-429c-4aa1-b19d-e3dedae01f96)

**Comment by mikeshasko** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/7a3ee4fe-e0a3-4800-8021-7e3ada1ab9ca)

**Comment by rajfreshworks** [comment]
Tested and the functionality is working as intended!
