### ISSUE TITLE
Release Inspect application to App Store

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#300]
**Describe the task**
get Inspect on the App store so it can be downloaded by our users in production

**Acceptance Criteria**
- [ ] Application is on app store
- [ ] Compile description of App and screenshots if we need to get it on the app store

**Additional context**
- Apple review can take up to 1 week

**Comment by mikeshasko** [comment]
@AmirShayegh 
@jakemorr 

- Who is the target audience?

**The application is to be used by approximately 200 BC Government Conservation officers and research scientists**

- How do users obtain an account?

**While many of the target users will have an account that can be used to login to the application, the application provides the link to our government site that can be used to acquire login credentials**

- Is this app meant for internal distribution in your own company, in the company of one target client, or in multiple target clients’ companies?

**This application is meant for internal distribution within a specific government agency but it is recognized that contracted resources will also be using this application**

- In which countries will this app primarily be distributed?

**Only Canada**

- If this app is meant for internal distribution, will the app be accessible by both internal and external partners? Or will it be exclusive to in-house employees?

**This application is meant fro internal distribution but will be accessible / required by a small set of external partners and sister agencies**
