### ISSUE TITLE
Residence of Boat returning wrong field

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#301]
**Describe the Bug**

**Expected Behaviour**
the dropdown contains provinces and states from Mexico/Canada/USA

**Actual Behaviour**
the dropdown contains 3 countries

** Steps To Reproduce**
Steps to reproduce the behaviour:

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jakemorr** [comment]
from Andrea:

This is technically done, but I don't think it's user friendly. Will be difficult for inspectors to know the 2-letter codes for states in USA or Mexico. See screenshot

Thoughts? Shasko, Michael FLNR:EX or XT:Jawl, Roop IIT:IN

**Comment by jakemorr** [comment]
from Roop:

Dont really see the reason to make these initials myself. My solution would require a new CSV though…

I'd prefer this dropdown is shown like:

Canada - Alberta
USA - California
MEX - Sonora

OR

CAN - AB
USA - CA
MEX - SO

**Comment by jakemorr** [comment]
from Mike:

Yes, proceed with a concatenation of the country code - Province Name as indicated by Roop's first suggestion.

The 2 character state/province code are not unique by themselves so the current drop down depicted in the screen grab will fail.

**Comment by jakemorr** [comment]
@AmirShayegh to do back end of this Ticket and @andrea-williams to do front end of this ticket.

We need to diversify skill sets

**Comment by andrea-williams** [comment]
![340601F3-6FAE-4524-B5A9-D1C9A7AFEA14_1_105_c.jpeg](https://images.zenhubusercontent.com/5e331ea54a0d32f8650c9a25/44e92057-7c8a-4a04-b7f4-e0302f35cbac)

Dropdown not working on front-end: only the shadow of the dropdown is displayed. See attached screenshot from iPad

**Comment by andrea-williams** [comment]
Have confirmed that this bug has been fixed.
