### ISSUE TITLE
Implement Metabase

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#308]
**Describe the task**
Implement Metabase with our remote database

**Acceptance Criteria**
- [x] Given we open Metabase When I look at our Database Then I can see its contents.
- [x] Metabase has its own link 
- [ ] can authenticate using Github to access Metabase

**Comment by micheal-w-wells** [comment]
@jakemorr I can share the config for range when it comes up

**Comment by rstens** [comment]
So GitHub authentication is not yet supported

**Comment by micheal-w-wells** [comment]
@rstens GH auth is a nice to have but I'm curious if it's even an option currently supported.  If you can't find anything on it you can close this issue, again nice work getting that one done in a hurry.
