### ISSUE TITLE
RISO Persona

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#309]
**Describe the task**
Create a persona for the RISO user group

**Acceptance Criteria**
- [x] Create Proto-Persona using existing team knowledge and resources
- [x] Persona based on sample of User Group
- [x] Outlines user Group Needs
- [x] Outlines User Group Challenges
- [x] Outlines Current applications in use
- [x] Outlines Communication Channels
- [x] Includes Nice Picture and Funny Name

**Comment by roopfw** [comment]
I've had a conversation with Mike about this persona as well as created some interview questions for a future interview.

[RISO Persona Notes and Questionaire](https://docs.google.com/document/d/1VY2d9HFKrPjBRXuJ-wi_w3l_ZuFOxSWxK97oPpH21Fg/edit#heading=h.yzvrwe2h9ydk)

![1.5 Persona - Regional Invasives Species Organization.jpg](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/d268948b-a2f2-494c-bbed-7ee786bd77d6)

![Regional Invasives Species Organization - Planning Journey R1.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/5cb5e23a-836f-47a8-b899-892dadee2b87)

**Comment by roopfw** [comment]
Please have a look @mikeshasko! I've got the persona in a MIRO board as well.

**Comment by mikeshasko** [comment]
Looks super.

Some edits:

... funded   change to partial funded

...location vancouver .... change to Whistler

Ho does she report out to her RISO board

and how does the RISO report out to the ISCBC (parent organization)

and how does the RISO need to report to MOF to retain/meet the requirements to ensure funding

and how does the RISO report out to their public community (ie their web site)

**Comment by roopfw** [comment]
Updated based on feedback:

https://miro.com/app/board/o9J_ky-0RvQ=/

![1.5 Persona - Regional Invasives Species Organization R2.jpg](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/857d8556-bb1d-40d4-ad13-8a874630cede)

**Comment by roopfw** [comment]
Updated for you @mikeshasko
