### ISSUE TITLE
Confirm RISO User Journey Map

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#310]
**Describe the task**
Create a journey map for the RISO Persona, to describe their work from the office to the field focused on the management of treatments

**Acceptance Criteria**
- [x] Draft questions
- [x] confirm questions with PO
- [x] Conduct Interview with Claire and Barb
- [x] Distill results
- [x] Create artifact which displays RISO Journey

**Additional context**
- Government has asked this before and RISOs still feel their role is not well understood, hopefully we can create something that highlights their role.

**Comment by roopfw** [comment]
![1.5 Persona - Regional Invasives Species Organization R2.jpg](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/ebe077e9-86bb-460e-9296-db1d16c1bd85)
[Regional Invasives Species Organization - Planning Journey R1](https://app.zenhub.com/files/181950649/9d3cc5f1-eacf-4deb-a310-ed2eb453a1a4/download)

**Comment by roopfw** [comment]
Review completed by Claire and Barb– updated based on their comments I might put together a quick document of notes to go along with this next sprint some good takeaways…

![Regional Invasives Species Organization - Planning Journey R2.png](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/1a673810-b10e-44e9-88f1-3b829d7cd148)
