### ISSUE TITLE
Errors in Create Observation fields

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#311]
![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/803a0bdd-70a4-4217-9d2b-cdea8a7402ff)**Describe the Bug**
With the create observation form 2 errors persist:

#1 The Agency list is in reverse order

#2 The "species distribution" field shoulds say "Observation Type"

See attached screen grab

**Expected Behaviour**

**Actual Behaviour**

** Steps To Reproduce**
Steps to reproduce the behaviour:

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/74d08abe-1df4-4ded-8838-3d0ac8e2887e)If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by andrea-williams** [comment]
Have confirmed that both bugs in this ticket have been fixed.
