### ISSUE TITLE
InvasivesBC Planning research

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#312]
**Describe the task**
Review Planning needs of the different InvasivesBC user groups 

**Acceptance Criteria**
- [x] Define the needs of planning for our application (what won't we do)
- [x] Review Planning interviews we have done previously
- [x] Basic framework for Planning workflows
- [x] Documentation/diagram of "how" planning could happen
- [ ] Review results with User Groups

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by roopfw** [comment]
Created a document to outline how users could plan within the InvasivesBC web application.

I kept the solution MVP with statuses driving the actions within the application. I would ideally like to flesh out how this would work with a mapping component (ie draw an area and assign all the observations in the area that require treatment to a user).

[**Google Document**](https://docs.google.com/document/d/10SMaGlpLggwf7aiV7G7DR-fkBJ1uKO1vZbrHqtd2IXQ/edit?usp=sharing)
[**Draw.io Diagram**](https://drive.google.com/a/freshworks.io/file/d/1-pOzzCaD6EEzja0vVBkXto4dOPunJpg6/view?usp=sharing)
