### ISSUE TITLE
InvasivesBC iPad App - Landing/navigation page

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#328]
As a User of InvasivesBC Ipad App I want to see an "Activity Panel" with functions as buttons so that I can proceed to add content.

**Additional Context**
Buttons within the Activity Button

- Create Invasive Plant observation
- Create invasive Plant treatment
- create invasive Plant monitoring

- create invasive Animal observation
- create invasive Animal treatment
- create invasive Animal monitoring

**Acceptance Criteria**
- [ ] Given I press on the application icon when I enter the app then I am presented with these 5 options
- [ ] Given I am on the landing page when I press any of the above buttons then I am navigated to the related page of the application
- [ ] Developers designs landing page to incorporate these things, Developer runs it past Roop before implementing

**Comment by fwpushan** [comment]
Basic Layout

https://docs.google.com/drawings/d/1iszKyf3GQJ7U1lG8g5tkmFSx4zE0RP0xW8mY11buExU/edit?usp=sharing
