### ISSUE TITLE
Chemical Monitoring

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#344]
As a Invasive Plant specialist i want to add a monitoring record to a treatment to reflect how effective a specific treatment was so that i can determine whether this treatment area requires follow up treatment, monitoring, etc.
JIRA 984 / 1065

**Additional context**

- Has been designed but must be implemented
- Blocked until design questions are resolved & mockups are updated based on SME feedback...
- Efficacy applies to each species individually or the treatment as a whole.
- Defer requests for type of efficacy rating for now

**Acceptance Criteria:**

- [ ] Monitoring record is added from treatment screen
- [ ] Treatment record selected must be a Chemical Treatment
- [ ] location is filled by user
- [ ] I can fill in Monitoring details including Treatment efficacy % for the treatment overall

**Comment by mikeshasko** [comment]
The 2 supporting JIRA tickets had a combined estimate of 5
