### ISSUE TITLE
Biological Monitoring (web)

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#346]
As an SME i want to be able to record biological monitoring information through the web interface.

**Acceptance Criteria**
- [ ] determine if this is required AFTER the mobile implementation
- [ ] confirm and review with Susan / Sandy
- [ ] third

**Additional context**
- This likely would be done through the mobile interface.

**Comment by valmill** [comment]
primary focus needs to be biological monitoring (for biocontrol agents) mobile as the work is done in the field.  Acceptance criteria needs to include Catherine MacRae and Val Miller.
