### ISSUE TITLE
Research MDS Implementation of Metabase as a query tool for users

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#351]
**Describe the task**
Research what MDS has done with metabase, also research is Metabase could be implemented to handle queries into our DB without the user typing in SQL 

**Acceptance Criteria**
- [ ] meet with MDS team to get a demo of how they use metabase
- [ ] research Metabase as a tool and determine if it meets our advanced search needs
- [ ] share findings with the team
- [ ] create any follow up tickets

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by thegentlemanphysicist** [comment]
Useful link:
https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html
Adding filters to metabase

**Comment by matthewhall78** [comment]
If you want to look at something simple, we put this together for a metabase quickstart guide: https://github.com/bcgov/nr-metabase-showcase
