### ISSUE TITLE
Database cleanup

### ISSUE THREAD

**Issue by rajfreshworks** [bcgov/lucy-web#353]
**Describe the Bug**
The CSV export functionality is filled with some garbage values which are unused fields in the database. A full cleanup needs to be performed and remove all those columns from the corresponding databases 

**Expected Behaviour**
As a user, when I click on export, I should only see the columns that were filled out

**Actual Behaviour**
The endpoint is returning the proper data along with some garbage values

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Admin tools` page
2. Click on `export`
3. Open up the downloaded file
4. See the CSV file have the following fields that are never used anywhere

Garbage fields

- watercraft_risk_assessment
   - decontamination_reference
- high_risk_assessment
   - general_comments

**Additional context**
We can groom this ticker further, if we come across any other garbage fields like this somewhere in our application, we can keep track of those here. It could help the developer with the cleanup process

**Comment by andrea-williams** [comment]
Classifying this as Critical since the Inspect app will be used by actual users in the field in the very near future.
