### ISSUE TITLE
restructuring folder structure

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#367]
**Describe the task**
restructuring folders to better group like components

**Acceptance Criteria**
- [x] Utilities/helpers should be one group
- [x] Reusable superclasses/ utilities should be part of a respective group /  one group called core which you can easily drag and drop to any other project
- [x] Data means JSON/text/plist should not be in a separate group and not part of any code related group.
- [x] Services and Managers should be in the same group 
- [x] Framework extension should be in one group 
- [x] Data Models should be in one group 

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by andrea-williams** [comment]
Folder restructure looks complete as far as I can tell.
