### ISSUE TITLE
Research Changing Keycloak Realms

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#369]
**Describe the task**
research how we could go about changing keycloak realms or restricting access to different BCeID types

**Acceptance Criteria**
- [ ] document in other BCeID ticket on how to restrict access to only Business BCeID users
- [ ] add any additional tickets if required

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by mikeshasko** [comment]
Aaron Canuel has confirmed that all Inspect Conservation officers/users have only IDIRs - we can defer BCeID work on the inspect app 🙂
