### ISSUE TITLE
incorporate Planning feedback into research

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#370]
**Describe the task**
incorporate planning feedback form review

**Acceptance Criteria**
- [x] incorporate feedback from sprint review

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by roopfw** [comment]
Worked feedback into the status workflow:

Requires a conversation with Mike and then SME's to validate.

[Draw.io Document: (V2 Tab)
](https://drive.google.com/a/freshworks.io/file/d/1-pOzzCaD6EEzja0vVBkXto4dOPunJpg6/view?usp=sharing)
![InvasivesBC - Planning Flow Diagram-V2.jpg](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/de706e32-3f5d-4a4e-ac71-b8c215476feb)
