### ISSUE TITLE
outline features from sprint review feedback

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#373]
**Describe the task**
draft stories for the features suggesting in review regarding planning

**Acceptance Criteria**
- [x] review sprint review tape to gather suggestions
- [x] reach out to stakeholders if suggestions are unclear
- [x] draft tickets for the suggestions (even if we wont be doing them) 

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by roopfw** [comment]
Created document to outline feedback:
https://docs.google.com/document/d/14MPEZlUX6VKwJ2-jHAd8N5F8MScDr9QUy3WJb7aYZNg/edit?usp=sharing

Creating tickets now…
