### ISSUE TITLE
Seed InvasiveBC Test DB with observation records

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#387]
**Describe the task**
Add 595 record to InvasivesBC test DB so we can start testing queries and map features

**Acceptance Criteria**
- [x] these records are in the DB on Test
- [x] when API is built it includes Seed data
- [x] file has lat long and will need to be converted and stored as spacegeom
- [x] also include calculating Hex ID for seed data

**Additional context**
- All records are observations
- we will need to have a flag so this doesnt go to prod

Seed data from IAPP (combined site/survey > observation)

https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/52265769/migration_v1_April16.csv?api=v2

Updated to include "none" for blank "Access description"
https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/52265769/migration_v2_Apr17.csv?api=v2

**Comment by mikeshasko** [comment]
The CSV has been created ... I'm doing some QC on it specific on the dropdown contents
