### ISSUE TITLE
iOS - Bring location services from web

### ISSUE THREAD

**Issue by AmirShayegh** [bcgov/lucy-web#389]
**Describe the task**
We have code conversions between Lat long, Albers and UTM coordinate systems in our web application that need to be translated to Swift for our iOS application

**Acceptance Criteria**
- [x] Lat long to Albers
- [x] Alber to lat long
- [x] Lat Long to UTM
- [x] UTM to Lat Long
- [x] inside BC outside BC
- [x] HexID

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by fwpushan** [comment]
Please fix all warnings in LocationService
