### ISSUE TITLE
Inspect app - Martina 1/6 - Ocean addition

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#392]
Journey details: the previous and destination waterbody – “ocean” needs to be an option in the drop down list for both or as a toggle field

[https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/52265769/ALL_NA_Lakes_Cities_v5_OnlyOceans.csv?api=v2](url)

**Acceptance Criteria**
- [ ] six ocean locations added with appropriate support data fields
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by fwpushan** [comment]
Test Steps:
With PostMan:
 1. check api/mussels/water-body
 2. Set env Remote-Dev
 3. Check 'Ocean Pacific BC' is exists in response. 

With iOS app
 1.  Download the TestFlight app which pointing to dev env (ask Amir)
 2. Create Inspection 
 3. Check water-body dropdown

**Comment by jakemorr** [comment]
I think we should test this all the way to the point of export.

**Comment by fwpushan** [comment]
Deployed

**Comment by mikeshasko** [comment]
tested / reviewed Apr 21 v439

6 ocean fields present / active / seachable
