### ISSUE TITLE
Inspect app - Martina 2/6 - Passport

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#393]
**Describe the task**
Passport information: if "no" is selected, need a toggle field for “Was a passport issued?” and if "yes" is selected, then another field which is alpha numeric is needed to enter the passport number.

**Additional context**
We want to be able to know if a new passport is issued and if so what is the new number. This is a work flow addition spawned off the initial response "Is this a passport holder ? > NO"

**Add a y/n toggle that asks "Was a passport issued?"  If YES the open the passport number field to capture the value BUT store it in the existing passport number variable in the DB.  If NO, then population the existing passport number variable with "Not Issued".  Under this scenario, the y/n toggle would not need to be a new variable addition to the DB. The default contents of the passport number would be "Not issued"**

**Acceptance Criteria**
- [ ]  the add "Was a passport issued" appears if "No" on the Passport holder is selected.
- [ ] the passport number becomes "not issued"
- [ ] a new number can be added... if none is added the "not issued" is stored in the DB

**Comment by mikeshasko** [comment]
Mike:  We’ll have to look at the passport workflow. If they don’t have a passport (with them) then you follow up by asking “was one issued” then you ask for the number … it seems unlikely they would know the number?

Martina - Sorry just to clarify if they don’t have a passport the field “was a passport issued” is when we are issuing a new passport to someone and the passport number is for the new passport that is issued. Does that make sense?

**Comment by jakemorr** [comment]
this seems outside of the realm of inspection,

how are issuance and tracking of passports currently handled by officers? why isnt the current method sufficient?

**Comment by ZoeSimon** [comment]
Short term work around is to deal with passport number in comment field, long term we will re-visit the workflow to incorporate passport options. - Mike Shasko

**Comment by mikeshasko** [comment]
@fwpushan 

The pop up flow seems to stem of "YES" rather than "NO" but if YES is selected then the popup asks if a passport was selected ... if yes YES is selected then the full report is presented (GOOD). If no then it goes to the short form (GOOD).

I believe this should be sufficient to capture the user story.

**Comment by ZoeSimon** [comment]
Text will now be changed to "Was a new passport issued"
