### ISSUE TITLE
Inspect app - Martina 3/6 - decontamination order

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#394]
**Describe the task**
The decontamination order number, record of decontamination number and the seal number need to be mandatory fields when the toggle is "yes", and an error should come up if these fields are not filled out and should not be able to save the record. 

**Acceptance Criteria**
- [ ] Record is incomplete until decontamination number and seal number are provided
- [ ] If decontamination or seal number is unknown, allow for "0" to be entered

**Comment by jakemorr** [comment]
This is a lower priority, can be handled by officer workflow, by ensuring officers know they are expected to fill these field out.

**Comment by davidclaveau** [comment]
Completed in this PR: https://github.com/bcgov/invasivesBC-mussels-iOS/pull/234
