### ISSUE TITLE
Inspect app - Martina 4/6 - Field display

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#395]
The number and alpha-numeric fields are not easy to see (no shaded box) hard to notice that it needs to be filled out (watercraft registration, passport number, days since previous inspection)

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by jakemorr** [comment]
sounds like a bug that we should fix, could we get a screen shot? @Martinabeck252

**Comment by Martinabeck252** [comment]
I have attached a screen shot and it's the record of decontamination number field. You cannot see the actual field where the values need to be entered

**Comment by ZoeSimon** [comment]
@mikeshasko 
"Attached is a screen shot that shows the record of decontamination field that is very difficult to see. This is an issue for any of the numeric/alpha numeric fields that need populating. As we talked about even just having a black border around the field to make it more obvious." - Martina

![IMG_0319](https://user-images.githubusercontent.com/62561887/79901534-ce86f080-83c4-11ea-8f0a-6af483c20b1f.PNG)

**Comment by AmirShayegh** [comment]
Fixed by 364
