### ISSUE TITLE
Inspect app - 5/6 - Standing water

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#396]
When “standing water present” is toggled as “yes” and you select an option from the drop down of where standing water was found (e.g. ballast tanks) this same selection (Ballast tanks) then populates in the field for “other inspection findings”. You then cannot change this field to be blank and have to change it to another option on the drop down list. The same thing happened when I filled out the field for where mussels were found it auto-filled this same selection under “other inspection findings

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by AmirShayegh** [comment]
To clarify:
When an option is selected from a dropdown, there should be a way to unselect/select none?

**Comment by mikeshasko** [comment]
Correct. If the selection is made in error, we need to be able to revert to unselected.

**Comment by AmirShayegh** [comment]
![IMG_FA36544DEF11-1.jpeg](https://images.zenhubusercontent.com/5e66ca826d0e6d231f80c5e1/5c0627d2-80f1-4d98-8a0d-ae0dc190ff5a)

**Comment by AmirShayegh** [comment]
Will be available in TestFlight soon
