### ISSUE TITLE
Inspect app - Martina 6/6 - Selection orders

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#397]
As a Inspect App user I want to select multiple options from the location drop down menu (i.e. select gimbal area and engine intake) so that I can accurately say the location that I found standing water & mussels.

**Acceptance Criteria**
- [ ] Given that a user had found standing water or mussels when they select the location then they can select multiple locations on the water craft.
- [ ] Given that I am exporting data from the database when I look at the standing water or mussel locations then they appear in separate columns in CSV. 

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by davidclaveau** [comment]
Completed in this PR: https://github.com/bcgov/invasivesBC-mussels-iOS/pull/238
