### ISSUE TITLE
InvasivesBC Fieldwork App Storyboarding

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#401]
**Describe the task**
storyboard of new InvasivesBC data collection app

**Acceptance Criteria**
- [x] structure of the app from the UX perspective
- [x] share with team
- [ ] name app (emoji poll)

**Comment by roopfw** [comment]
Completed Workflow…
[https://app.zenhub.com/files/181950649/7ac2a329-29a0-4dd6-bd69-4aaf2aca25e4/download](https://app.zenhub.com/files/181950649/7ac2a329-29a0-4dd6-bd69-4aaf2aca25e4/download)

**Comment by roopfw** [comment]
After a tremendous polling session

The app with henceforth be called:

### InvasivesBC Fieldwork App

**Comment by ZoeSimon** [comment]
Addition of pre-planning (Caching for the work day area of interest).

**Comment by roopfw** [comment]
Updated flow based on feedback:

![InvasiveBC Mobile - Flowchart 1.0.jpg](https://images.zenhubusercontent.com/5e66ca845237f60c730a4aa3/b6348731-2d79-46a9-97fb-1e0cd44530ff)

**Comment by ZoeSimon** [comment]
@victorchong Something that might of of interest for you.
