### ISSUE TITLE
Edits to the CSV output file from the Inspect App

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#411]
As an Inspect admin I want to see a revision to the content / order / field names of the exported file to be able to complete my offline Inspect analysis

**Additional Context**
Confluence link to the xls file that has the required edits:

https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/52265769/Inspection%20App%20CSV%20Changes_Apr%2005%202020.xlsx?api=v2

**Acceptance Criteria**
- [ ] add the fields noted in red
- [ ] have the order of the csv mimic the xls listing
- [ ] rename a few noted fields in the csv header

**Comment by fwpushan** [comment]
@mikeshasko @jakemorr 
Regarding refactoring of columns previousJourneyDetails/ destinationJourneyDetails 
These two columns represent a list of water-bodies not possible to represent in separate columns.

**Comment by AmirShayegh** [comment]
Shift columns are out of order
`Time of Inspection` should be after `Passport Holder` column
`Province of Residence` field should be after` Record of Decontamination Number` column
High-risk columns are out of order
Extra Shift column
`no boats inspected` Column is missing from export
