### ISSUE TITLE
Journey details - Martina 

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#414]
**Describe the Bug**
Once the toggle is selected as yes for “commercial manufacturer” “unknown waterbody” or “previously /being stored” for both previous and destination waterbodies the toggle is locked and cannot be changed. Need to be able to edit these selections. 

**Expected Behaviour**
When toggles are selected it should not be locked and I should be able to change my selections.

**Actual Behaviour**
When toggles are selected they are locked

![IMG_35DF86FE9578-1.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/cd27d580-4f25-40f8-853d-e0b248a74099)

**Steps to reproduce**

**Comment by ZoeSimon** [comment]
Need to follow up with @Martinabeck252 as we are not able to reproduce this bug currently.

**Comment by Martinabeck252** [comment]
I must have been working off an older version, I am no longer getting this issue when using the latest version downloaded from iStore
