### ISSUE TITLE
Inspect app - request to Invasives for access

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#415]
**Describe the Bug**
Inspect app - the request to Invasives for access on the current iOS release does not apprear to be showing up.
Both Martina and Mike attempt this Apr21 on v439

**Expected Behaviour**
Access request o show up in the web admin tools

**Actual Behaviour**
No indication that someone is waiting on Inspect access

** Steps To Reproduce**
Steps to reproduce the behaviour:

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by AmirShayegh** [comment]
If the TestFlight version was installed on the device, it should be deleted before installing the App Store version. 
App Store version of the application is pointing to our prod environment. 
Please use [`The production url`](https://invasivesbc.pathfinder.gov.bc.ca/admin) to allow access
