### ISSUE TITLE
Inspect Access for launch

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#429]
**Describe the task**
Ensure Martina and other Mussel stakeholders have appropriate access for start of inspection season.

**Acceptance Criteria**
- [x] Confirm Inspect admin has "Admin Access" and access to Inspect application
- [x] Confirm that Martina & Stakeholders have appropriate access level
- [ ] Call and confirm with Martina that she's able to manage access levels

**Comment by roopfw** [comment]
Confirmed access… Good to go.
