### ISSUE TITLE
Create an Invasive Plant Observation Mobile Part 1

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#430]
**Describe the Task**
Open the geometry capture modal.

**Additional Context**  Workflow
- define the collection of the geometry first and once confirmed display the input modal

**Acceptance Criteria**
- [ ] The geometry that is created is complete
- [ ] Once confirmed, proceed to data collection

**Comment by mikeshasko** [comment]
Loaded the testflight version 1.0
Feature(s) not available
