### ISSUE TITLE
Planning for User Research on Web App

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#434]
**Describe the task**
Planning for User Research on Web App. Observation + Treatment.

**Additional Context**
World tour!

**Acceptance Criteria**
- [x] Create testing plan
- [x] Send out invites

**Comment by roopfw** [comment]
### Document completed with testing plan:
https://docs.google.com/document/d/1Qg8UQFZM3GrBNx2jALHmPwEKEtdFymuxiP32aNiNGuo/edit#heading=h.iwdks9ab1jve

### Invitations sent out: 

1. Kalyn May
2. Emily Sonntag
3. Janine Bond
4. Jazmine Lowther
5. Crystal Chadburn
6. MacRae, Catherine FLNR:EX
7. Denise Mclean
8. Sheryl Wurtz
9. Grahame Gielens

**Comment by roopfw** [comment]
Putting together the data sheet for testers– with content to fill in forms.
