### ISSUE TITLE
Test Coverage 

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#456]
**Describe the task**
Test Harness for all major pieces (obtain information about test coverage about each component):

**Acceptance Criteria**
- [x] Is there decent test coverage?
- [x] If yes, is there a meaningful name for the tests?

**Comment by ZoeSimon** [comment]
May need to break this ticket into separate tickets during Backlog refinement

**Comment by ghost** [comment]
I have added the test coverage for both the backend and the frontend major pieces. A separate ticket is created to capture the ios related work on this

https://docs.google.com/document/d/1GkywcJ4vSS8KLHlBwr7liV_XYgfGWiskWmREnCh06MM/edit?usp=sharing

**Comment by andrea-williams** [comment]
Have reviewed this doc - looks good for now, but will likely require significant updating once we have implemented E2E testing with Cypress. 

Again, strongly recommend that this Google Doc gets converted to markdown so that it can be added to our github repo and updated easily.
