### ISSUE TITLE
Write missing tests we need

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#457]
**Describe the task**
Test Harness for all major pieces
- [ ] Write missing tests we need

**Comment by micheal-w-wells** [comment]
Will sound like a broken record - and I apologize - but i think a big bulleted + sub bulleted list of features is the place to start for a health check on feature tests.  

Organize them based on how important they are, and as dev peers decide:  
Does this feature have adequate tests and do they have meaningful names?  

For the low priority ones breadcrumbs will have to do if there are no tests, but ideally we keep that to a minimum if you want the next squad to not accidentally break things and be stuck in the mud.

For the big end to end pieces, outline what the big user workflow is in manual testing, and break it into chunks that a user would understand (auth/login, going to new observation page, etc).  The value in these tests is that they let you know what step failed, vs one big test that says "main workflow failed".
