### ISSUE TITLE
Document what we are considering major pieces

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#477]
**Describe the Task**
Test Harness for all major pieces:
- [ ] Document what we are considering major pieces
- [ ] create a document that we can build off of to physically hand off as a reference piece for the next team

**Comment by ghost** [comment]
I have created this doc and added the major pieces from the backend, frontend and a little bit about ios application and the pipeline. 
https://docs.google.com/document/d/1x7rLw_l8oo0OUcs8d6viA52PsIK0qdwUJkNRHWpUos8/edit#

@AmirShayegh @fwpushan @andrea-williams Please take a look and let me know if you any changes required. Amir or Pushan, Can you update the doc for mobile apps and pipeline?

To download the doc, 
https://github.com/bcgov/lucy-web/blob/dev/documentation/docs/InvasivesBC%20-%20Major%20pieces.docx

**Comment by ghost** [comment]
Created follow up tickets to capture ios and pipeline related works
