### ISSUE TITLE
Research how other teams are managing Load testing

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#479]
**Describe the Task**
Load Testing API:
- [ ] Research how other teams are managing Load testing

**Comment by rajfreshworks** [comment]
Based on the conversation I had with different people, 

It's advised that we use the npm package [load test](https://www.npmjs.com/package/loadtest) to perform the load testing on our endpoints. I looked at the package on how to use it, it is very straightforward and easy to use. It can be easily integrated with our current testing framework (Mocha) to perform the testing on any or all of our endpoints easily

**Additional Context**
From Jeff Arctiq,

`Just poking my nose in here to say Awesome! and to add a tidbit for your load-testing...
Load test against a single pod deployment and try to find your break-points (ie: when performance is too low, or when errors start happening)
Then, measure your mem/cpu at the break point to tie your request/limits there
Then you're ready to look at AutoScaling your deployments with the Horizontal Autoscaler!`
https://docs.openshift.com/container-platform/3.11/dev_guide/pod_autoscaling.html

**Comment by ghost** [comment]
Google doc for load testing reference

https://docs.google.com/document/d/15BTszxDMeWqqTVXGgPfjTcg2_l547CM9dLZED3MCBWE/edit?usp=sharing

Download the doc from this link,

https://github.com/bcgov/lucy-web/blob/dev/documentation/docs/InvasivesBC%20-%20Load%20testing.docx
