### ISSUE TITLE
Inspect bug report (Pradeep Poudel #1) Ocean

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#483]
**Describe the Bug**
An issue is reported by user pradeep.poudel@gov.bc.ca.
Message From User: Ocean Pacific closest cities are only Seattle & Vancouver, need other states, Vancouver Island, and Yukon.

Mike's notes:

The Water body "Pacific Ocean" is the intended element that needs to be captured. The closest city is only used to identify the nearest city to help differentiate the water body.

At this time no action is required to address this as the user suggests.

**Comment by mikeshasko** [comment]
Existing water list.  Please add any new items - orange = required from Martina / Aaron

![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/09af4172-a61e-4a78-bff9-95dacac2758a)

**Comment by Martinabeck252** [comment]
I have tried to attach the list of additional ocean/city combinations for adding to the list but i don't know if the attachment worked 
[ocean drop down list.pdf](https://github.com/bcgov/lucy-web/files/4652514/ocean.drop.down.list.pdf)

**Comment by mikeshasko** [comment]
Updated list in preparation as of May 19th ... SEE Mike

**Comment by mikeshasko** [comment]
https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/52265769/ALL_NA_Lakes_Cities_v5_OnlyOceans_V3.csv?api=v2

Update to oceans names (May 20th)

Please remove/replace all existing Ocean records with this one all-inclusive list.
