### ISSUE TITLE
Inspect bug report (Pradeep Poudel #3) 30 day

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#486]
**Describe the Bug**
An issue is reported by user pradeep.poudel@gov.bc.ca.
Message From User: For previous waterbodies, selecting the toggle for boats coming out of storage, please confirm it is only applicable for boats that have been stored for than 30 days? i.e. boats that were stored for 2 to 3 weeks should have a specific previous waterbody selected on the form, instead of toggled as "previously stored".

Mike's notes:

This requires a more explicit workflow defined for the inspectors as to handle this situation.

At this time no changes to the application will be considered.

**Comment by jakemorr** [comment]
this one could be as simple as a text change. but I agree, The officer should know this, the individual transporting the watercraft is not filling out the form them self
