### ISSUE TITLE
Documentation on workflow with expected behaviours for each step - Inspect App

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#494]
**Describe the Task**
Documentation on workflow with expected behaviours for each step in Inspect app

(falls under End to end test for Inspect app)

**Comment by micheal-w-wells** [comment]
Hi this one says ready to review, can I get a link posted here to the doc in question?

**Comment by AmirShayegh** [comment]
https://github.com/bcgov/invasivesBC-mussels-iOS

**Comment by micheal-w-wells** [comment]
LGTM
