### ISSUE TITLE
Review and note where bread crumbs would be valuable

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#495]
**Describe the Task**
Bread Crumbs
- [ ]  Review and note where bread crumbs would be valuable

**Comment by micheal-w-wells** [comment]
- what things are partly done
- what low priority stuff has no tests, but needs doc
- things that were not done, but anticipated to be needed later, and advice on changes that would needed to be made, such as:
    - what things would need to change if we moved to high availability i.e. more than one pod running your api.

**Comment by micheal-w-wells** [comment]
Nothing left to do on this one but #507, i think the 'identifying what a breadcrumb would be' part of it is long done.
