### ISSUE TITLE
Create end to end test using Cypress

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#502]
**Describe the Task**
End to end test for Web App:
- [ ] Create end to end tests using Cypress

**Comment by ZoeSimon** [comment]
Separate into multiple tickets during Backlog refinement

**Comment by ZoeSimon** [comment]
Gary Wong's links for Cypress E2E testing: 
https://github.com/garywong-bc/invasives-e2e-demo/tree/master
https://docs.cypress.io/guides/guides/continuous-integration.html#Setting-up-CI

**Comment by AmirShayegh** [comment]
The estimate is for using cypress tests we created for each page to perform a full end to end cypress test of the workflow: Create observation -> check inventory -> create treatment record for observation -> create monitoring record.
