### ISSUE TITLE
User Testing InvasivesBC

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#508]
**Describe the task**
Carry out user testing with invited participants. Present findings during sprint review. 

**Acceptance Criteria**
- [x] Compile data users will use to complete the testing
- [x] Run through testing with Mike Shasko
- [x] Complete user testing with participants who have accepted invitation
- [x] Fill out user testing document
- [x] Summarize key findings

**Comment by roopeyds** [comment]
### 2020-05 - InvasivesBC Web UX Test and Results

Online Version: [2020-05 - InvasivesBC Web UX Test (Google Docs)](https://docs.google.com/document/d/1Qg8UQFZM3GrBNx2jALHmPwEKEtdFymuxiP32aNiNGuo/edit?usp=sharing)

Downloadable Verion: [PDF Version](https://app.zenhub.com/files/181950649/4bada908-2a03-4769-977c-394f410cdff8/download)

### Key Takeaways

- **Mapping Component needs further refinement before primetime**
  - There were many bugs related to the display of the map in a record. The map displays no data by default. Once a record has been completed the map also breaks and does not display the location of the record. Users loved the feature but misse 
  - Various major bugs need to be fixed prior to handoff date.
  - There were a few bugs that caused critical errors throughout the testing process. Most prominent was the fact that chemical treatments could not be completed. If we are going to be pushing this an MVP product all main features should work as intended.

 - **Location entry as UTM/Latitude Longitude seemed confusing. The toggle seemed broken to users**
   - The Plot geometry settings were also broken and Plot - Length/Width saved as Plot Radius causing confusion to users.

- **Geolocation of records based on hex needs more work**
  -  Creation of any record that is not an observation seems broken to users. When selecting a plant to treat at a location the system shows ALL records within the database causing confusion. We need to complete the intended functionality of the system where the user would be shown only records within a certain radius of the location entered.
