### ISSUE TITLE
Add SonarQube back to the pipeline

### ISSUE THREAD

**Issue by rajfreshworks** [bcgov/lucy-web#511]
**Describe the Bug**
Now that we are making changes to the SonarQube, the Jenkins build fails for all the PRs. To bypass this, we ended up disabling the Sonar analysis script for both the web app and the backend.

**Expected Behaviour**
The Jenkins build should include the sonar analysis step and it should pass

**Actual Behaviour**
The Sonar analysis script fails

**Additional context**
Follow these steps here to add the sonar analysis back to our pipeline

1. For the web app, open the Dockerfile under `app/lucy`. 
    * Uncomment the line 34 to run the sonar-analysis again
2. As for the backend,
    * open the package.json in `api/api_sources` and delete the script  `remote:test-temp`
    * open the `test.pod.yaml` under `api/openshift` and on line 71 change the command to be `npm run remote:test`

**Comment by rstens** [comment]
This ticket is no longer valid. We do have a new one for updating and streamlining sonarcloud
