### ISSUE TITLE
Sync issues - Martina May 19

### ISSUE THREAD

**Issue by mikeshasko** [bcgov/lucy-web#515]
We encountered another issue over the weekend with the Inspect App that only a handful of the inspectors seem to be able to successfully sync and upload the data. A large portion of the inspectors are not able to successfully submit and upload a shift record, they receive the attached message saying that a sync cannot be completed. I have checked the data that has been uploaded and we only have data from two of the nine stations from this past weekend. It appears that the records are saved to the iPad but they are pending syncing. 

It seems as though the upload is working for a small portion of the IDIRs but it’s not working for the majority of the inspectors IDIRs. I tried to look via my admin function on the web to see if there were differences in their IDIR settings but there wasn’t anything that I could find to edit. 

Maybe its just a simple step that we are missing to enable the sync function? Some of the inspectors did try rebooting the App, changing WiFi connections and trying different IDIR’s and the data still would not upload. 

This of course if a high priority issue as we have a large number of data records from the long weekend that have not uploaded yet.

**Comment by mikeshasko** [comment]
![ipad sync error.jpg](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/1876b53c-0481-4135-983e-6b4fe2137d79)

**Comment by mikeshasko** [comment]
Fix API

Make the field optional

Contact all users (make sure none are using testflight version)

Sync existing data first
Update the app.

**Comment by ZoeSimon** [comment]
@mikeshasko Waiting to hear back from Stakeholders regarding Sync issues before closing ticket

**Comment by ZoeSimon** [comment]
Mike Shasko 9:50 AM:
The Inspect data report currently has 489 records from all over the province up to late yesterday. We can assume it is operational and can close the sync related issues.
