### ISSUE TITLE
Chem Treatment - Secondary Applicator should not be required field.

### ISSUE THREAD

**Issue by roopfw** [bcgov/lucy-web#523]
**Describe the Bug**
Secondary applicator is currently a required field.

**Expected Behaviour**
Only Primary Application is required field.

**Actual Behaviour**
There may not always be a secondary applicator present so it should not be a required field.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Create Chemical Treatment
2. Click on Submit
3. Error shown.

**Comment by ZoeSimon** [comment]
Should be enforced by API
