### ISSUE TITLE
Automated test for Invasives Web app - inventory (home) page

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#533]
**Describe the task**
Automated test for inventory (home) page in the Invasives Web app.

**Acceptance Criteria**
- [ ] Export functionality
- [ ] Basic search
- [ ] Navigate to single observation
- [ ] Toggle between table and map

**Additional Criteria**
- [ ] Does this test have a meaningful name
- [ ] Assertion in test does a good job of validating the business function worked

**Additional Context**
Build on what Gary Wong has provided for using Cypress.

**Comment by fwpushan** [comment]
@AmirShayegh Not able to execute the test in my local env
Getting error
```
Timed out retrying: cy.should() failed because this element is detached from the DOM.

<tr _ngcontent-dpq-c10="" class="mat-row ng-star-inserted" mat-row="" role="row" style="">...</tr>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.each()

This DOM element likely became detached somewhere between the previous and current command.
```

```
cypress/integration/inv-inventory/nav-inventory.spec.ts:60:26
  58 |         cy.wait(2000);
  59 |         cy.get('table').get('.mat-row').each($el => {
> 60 |             cy.wrap($el).should('contain', 'Spotted knapweed');
     |                          ^
  61 |         });
```
