### ISSUE TITLE
User testing for Mechanical Treatment & Monitoring, and Chemical Treatments

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#546]
**Describe the task**
Carry out user testing with invited participants. Present findings during sprint review. 

**Acceptance Criteria**
- [x] ensure that all bugs from previous testing has been added
- [x] Send invites to user testers
- [x] Complete user testing with participants who have accepted invitation
- [x] Fill out user testing document
- [x] Summarize key findings

**Comment by roopeyds** [comment]
I have summarized results and brought all elements of this round of testing together here:
[2020-06 - InvasivesBC Web UX Test - Mechanical Treatment](https://docs.google.com/document/d/1cfOMo6akYVz0b_cPOa4BhRX7AsrOXD__PGPE3NJG-UE/edit?usp=sharing)
