### ISSUE TITLE
Automated testing for Inspect iOS app - Creating a Shift

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#549]
@AmirShayegh please finish filling this ticket out 

**Describe the task**
Automated testing for creating a Shift in the Inspect iOS app.

**Acceptance Criteria**
- [ ] Create a shift, enter initial information (modal).
- [ ] Add Additional information to shift.

**Additional Criteria**
- [ ] Does this test have a meaningful name
- [ ] Assertion in test does a good job of validating the business function worked

**Comment by micheal-w-wells** [comment]
Cool to see we are able to work on UI tests for iOS in this sprint.  Which tool did you end up using again?  The Wix one or the stuff that comes with Xcode? @AmirShayegh
