### ISSUE TITLE
Cypress - Keycloak Authentication

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#552]
**Describe the task**
Cypress is now setup in a way that it uses the credentials of a test user account from keycloak. This needs to be modified to use either IDIR/BCeID to match our standard login criteria. Without this, it is not possible to test out few features based on permissions

**Acceptance Criteria**
- [ ] Remove the test credentials from "cypress.env.json"
- [ ] Add the login credentials for different account types i.e Admin, DV, DE, Inspect Admin
- [ ] Update the authentication command to handle different user accounts
- [ ] Test cases should now be run as if it is logged in with IDIR user account

**Additional context**
Seek guidance from Gary Wong if needed on how to integrate IDIR/BCeID with cypress-keycloak authentication

**Comment by rstens** [comment]
This issue has been solved by adding a pw in Keycloak for our IDIR test users.
Currently we have istest1 set up in this fashion.
The thing remaining here would be the addition of the test ids and roles to the test scripts.
