### ISSUE TITLE
add Test IDIR as admin

### ISSUE THREAD

**Issue by jakemorr** [bcgov/lucy-web#553]
**Describe the task**
the app admin IDIR is in the process of being reinstated, while that happens we need an IDIR with admin access so that it can provide other actual users with permissions

**Acceptance Criteria**
- [x] Mike can login with Admin access on his own IDIR
- [x] we have a test IDIR with admin privileges at-least temporarily

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by fwpushan** [comment]
###Test Steps

1. Login into OpenShift prod namespace / project 

2. Go to the Overview Page > invasivesbc-api-prod > invasivesbc-api-prod

3. Expand pods section

4. Select any ready pod 

5. Open terminal and run cmd **ts-node scripts/admin.ops.ts -i <IDR> -r ROLE**
