### ISSUE TITLE
Review Zap Scan results and fix warnings

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#580]
**Describe the task**
Review Zap scan results and fix warnings as outlined in tickets #567 & #568 . Determine which ones are most important to fix.

**Acceptance Criteria**
- [ ] Review Zap Scan results and determine priority for fixing
- [ ] Share priority & methods with team/Mike Wells
- [ ] Confirm with Jeff de Castro what requirements are

**Comment by micheal-w-wells** [comment]
Any luck on getting a criteria on which type/severity of warnings we need to act on?

**Comment by ZoeSimon** [comment]
@micheal-w-wells 

From: de Castro, Jeff IIT:EX
To: Simon, Zoe FLNR:EX
Subject: Re: InvasivesBC - ZAP Scan results

Generally our recommendation Highs and Criticals should be addressed as soon as possible, Low and Mediums can be added in an action plan to be addressed when possible.
