### ISSUE TITLE
Handoff UI/UX Elements

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#601]
**Describe the task**
Document and post to confluence the User testing and UI scripts developed to capture testing sessions with the stakeholders.

**Acceptance Criteria**
- [x] Graduation Inspect demo completed
- [x] Document outlines all other documents created during the project
- [x] Overview of design methodology for project
- [x] Overview of applications created
- [x] Copy any documents from google docs into confluence.

**Comment by roopeyds** [comment]
### Inspect Demo for lab graduation video available here: 
https://drive.google.com/file/d/14oYWuSr-ENv0LwfiuKcy8Yqg25FXTtuB/view?usp=sharing

**Comment by roopeyds** [comment]
### User Experience Overview Document
https://apps.nrs.gov.bc.ca/int/confluence/x/W4OBB

### User Experience Testing
https://apps.nrs.gov.bc.ca/int/confluence/x/fAiUAw
