### ISSUE TITLE
Logout feature not consistent

### ISSUE THREAD

**Issue by roopeyds** [bcgov/lucy-web#617]
**Describe the Bug**
User tried to logout but the system would keep taking her back to a logged in state.

** Steps To Reproduce**
Was not able to reproduce on my system. But is shown in user test video:
https://drive.google.com/file/d/1nYnyhaNiCEIEZReyMv0-DJctMbns2Y2S/view?usp=sharing 1:44:05

**Comment by rstens** [comment]
This is a known bug with siteminder/keycloak.
