### ISSUE TITLE
Inspect - Add character limit to comment fields

### ISSUE THREAD

**Issue by AmirShayegh** [bcgov/lucy-web#622]
**Describe the task**
Add character limit to comment fields - 300 chars

**Comment by ghost** [comment]
The test flight version did not allow me to edit inspections ... only the shift variable could be edited. Sync always failed with not mention of what was the cause. I was seeing multiple "invalid" popups in the upper left.

Character fields over 500 did flag the error and I was able to change them on the shift comments but the sync persisted to report x2 Invalid messages

**Comment by ghost** [comment]
tested via 1.5 589 on testflight
