### ISSUE TITLE
Create Plant Observation

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#628]
**Description/details:**
- [x]  Create table and fields:
  - Details: 
     - [x] Add the missing fields (See Image and InvPlants_July16_Schema_Tables.xlsx file in comment below)
    -  [ ] Add additional plant observation variables (i.e. negative observation flag, aquatic plant variables)
     - [ ] Add aquatic subform table and collection frame

- [x] Ensuring that authentication works with our endpoints
- [x] Make API operation
  - [x] Update API to include new fields
  - [ ] Input Validation Rules
        - All fields mandatory (if aquatic observation terrestrial fields will be null, and vice versa)
- [x]  Enforce which roles should be able to use the operation:
     - Details:
        - Data Editor access only
- [ ] Create test (Mocha for now, Postman for future)

**Additional Context:**
- Fields for both Terrestrial & Aquatic plants
- OLD/Incomplete structure : SchemaSpy link: https://invasivebc-schemaspy-deploy-8ecbmv-dev.pathfinder.gov.bc.ca/tables/observation.html

**Comment by ghost** [comment]
![Observation_Table_Extension1_July14.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/5de83d12-326f-4728-b0b7-f6e201d357c6)![Observation_Table_Extension2_July14.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/cb6c327d-05ed-48e2-a989-e4af07095d4a)[https://app.zenhub.com/files/181950649/3e09d6ae-bb54-4649-8ac6-702bd9b2cc81/download](https://app.zenhub.com/files/181950649/3e09d6ae-bb54-4649-8ac6-702bd9b2cc81/download)

**Comment by mikeshasko** [comment]
Updated look for the observation data input form.
I potentailly could fit on 1 page - certainly no more than 2.
![Observation_July16.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/449d1373-2d9a-490a-ab9b-2eaf3bee1337)

**Comment by mikeshasko** [comment]
[Uploading... InvPlants_July14_Schema_Tables.xlsx ]

**Comment by ghost** [comment]
[https://app.zenhub.com/files/181950649/2e0d33fb-f0f2-4eb0-a486-29fe6c0d6d58/download](https://app.zenhub.com/files/181950649/2e0d33fb-f0f2-4eb0-a486-29fe6c0d6d58/download)

**Comment by popkinj** [comment]
> ![Observation_Table_Extension1_July14.JPG](https://camo.githubusercontent.com/489a0a2bf37b310d56654f9d5f855dc5c3476fdb/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565366639613034313062646465353835633931393934362f35646538336431322d333236662d343732382d623062372d663665323031643335376336)![Observation_Table_Extension2_July14.JPG](https://camo.githubusercontent.com/d5c3fdd2dee15abcc81e390e6fc80442d9bde9a3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565366639613034313062646465353835633931393934362f63623663333237642d303565642d343865322d613938392d653461663037303935643461)https://app.zenhub.com/files/181950649/3e09d6ae-bb54-4649-8ac6-702bd9b2cc81/download

**Comment by popkinj** [comment]
Hey @mikeshasko 
Any idea what *hex_id* and *hex_sub_id* are used for. Says they're generated from the a point geometry... But they're named as IDs.

**Comment by popkinj** [comment]
Hey @ZoeSimon 
Is the info for the second two checkboxes of "create table and fields" also located in the spreadsheet?

**Comment by ZoeSimon** [comment]
> Hey @ZoeSimon
> Is the info for the second two checkboxes of "create table and fields" also located in the spreadsheet?

Hmm let's see if @mikeshasko knows?

**Comment by ghost** [comment]
yes - Is the info for the second two checkboxes of "create table and fields" also located in the spreadsheet


[https://app.zenhub.com/files/181950649/6df5000c-6829-454a-bd72-35debc834036/download](https://app.zenhub.com/files/181950649/6df5000c-6829-454a-bd72-35debc834036/download)

**Comment by popkinj** [comment]
Hey @mikeshasko 
Unfortunately I can't open that file.

I get the new table bit now.
But the plant observation attributes... Are those the ones at the bottom of the *observation* spreadsheet?... coloured in brown?

Thanks ☺

**Comment by micheal-w-wells** [comment]
Much of this work is getting recycled into the new generic activity endpoint, work remaining is: captured in linked issues below:

**Comment by micheal-w-wells** [comment]
Observation API validation rules:

- [ ] Make the Create Activity endpoint do validation on both common observation fields as well as those specific to a terrestrial plant observation

**Comment by micheal-w-wells** [comment]
Observation API Mock Request/Mock endpoint

- [ ] Get a sample observation (create activity > type observation > subtype terrestrial plant) request together for the mobile team to use as a template for integration
- [ ] Put it in postman so it can be a mock endpoint for them.
