### ISSUE TITLE
Create endpoint/API Operation to read Activities

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#629]
**Description/details:**

- [ ] Make API operation
- [ ] Enforce which roles should be able to use the operation:
- [ ] Grab whole Activity table by I.D.
- [ ] Create test

**Comment by ghost** [comment]
Sample look at the frame to review an observation upon the creation of an observation.
This would also be the same frame called up via the status page to edit an observation.

![Observation_Review_July19.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/2b7d8b55-bdc1-445d-9f3a-78157b9b6c72)

**Comment by ghost** [comment]
![Aquatic_Review.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/650be134-332f-4522-9d43-9c385607bf32)

**Comment by micheal-w-wells** [comment]
work for v1 is done
