### ISSUE TITLE
Update Activity Operation/ API Endpoint

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#630]
**Description/details:**
- [x] Make API operation
- [ ]  Enforce which roles should be able to use the operation:
  - Details:
    - Data Editor access only
- [ ] Enforces same  Input Validation Rules as create activity endpoint
- [ ] creates new version of activity record.

**Comment by ghost** [comment]
Sample look at the frame to review an observation upon the creation of an observation.
This would also be the same frame called up via the status page to edit an observation.

![Observation_Review_July19.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/c749ec9b-b1b7-4895-b123-59df9bd3e2c2)

Validation rules:

[https://app.zenhub.com/files/181950649/375ce376-dce1-4689-9e3f-b17206ceff0c/download](https://app.zenhub.com/files/181950649/375ce376-dce1-4689-9e3f-b17206ceff0c/download)

**Comment by micheal-w-wells** [comment]
Mobile form input validation rules for create plant observation

**Special rules:**
- [ ] The "commit" selection sets the data for sync'ng. The user is sent to the "Status" page.
- [ ] Some fields would not be allowed to be changed:
  - Negative observation (whether yes/or no) should be greyed out. 
  - Aquatic indicator (whether yes/or no) should be greyed out. 
  - Latitude and Longitude should be greyed out. 
  - Well distance / and tag number should be greyed out. 
  - Area and geometry type should be greyed out.
