### ISSUE TITLE
Delete Plant Observation

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#631]
**Description/details:**
- [ ] Make API operation
- [ ]  Enforce which roles should be able to use the operation:
  - Details:
     - Data Editor access only
- [ ] Create test
- [ ] The option to delete a record (prior to sync) is available off the status form

**Comment by popkinj** [comment]
Deleted/Archived column - Boolean
Deleted_at/Archived_at column - Timestamp
