### ISSUE TITLE
Create Plant Observation - Mobile

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#652]
**Description/details**
- [ ] Depends on API Create Observation #628
- [ ] Read, update and delete pre-sync only
- [ ] Fields for form:
   - Details:  The observation data fields have been illustrated in the mock-up (see comment)
- [ ] Includes capturing geometry
- [ ] Create Test

**Additional Context**
- [ ] fields common to both terrestrial & aquatic plants, not species specific forms
- [ ] requires the creation of the aquatic sub form
- [ ] The specific behaviors are noted by the type of input field.
- [ ] Present design option to @mikeshasko 

Related to #824
This issue blocks #629 and  #630

**Comment by ghost** [comment]
Updated look for the observation data input form.
It potentially could fit on 1 page - certainly no more than 2.

![Observation_July16.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/8acf2df4-df7b-4638-9fc5-8a3c72ec9fec)

**Comment by ghost** [comment]
![Aquatic_Capture.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/0606804a-9baa-4b6d-9bea-05b74f485f9b)

**Comment by anissa-agahchen** [comment]
TO DO:
* Geometry is populated with the geometry the user selects
* All data fields need to be stored to realm
* On the read-only page, display boxes around the fields to improve readability

**Comment by anissa-agahchen** [comment]
TODO:  Understand why MapExtension.swift is almost identical to GeometryPickerMapDelegate.swif, with the except to the function.  This might be something that needs to be cleaned up.

In GeometryPickerMapDelegate.swift:
extension GeometryPickerViewController: MKMapViewDelegate{...
![image](https://user-images.githubusercontent.com/22803003/90927766-8a275380-e3aa-11ea-9fd6-284e002ed6fe.png)

In MapExtension.swift
extension LaunchViewController: MKMapViewDelegate{...
![image](https://user-images.githubusercontent.com/22803003/90927975-df636500-e3aa-11ea-884a-63ee0f4bf15e.png)
