### ISSUE TITLE
Forms: Finalize Terrestrial Plant Mechanical Treatment form

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#653]
**Describe the Task**
Ensuring the form content and behaviour is accurate for Creating a Terrestrial Plant Mechanical Treatment.

This is finalized workflow design/concept for the Terrestrial Plant Mechanical Treatment.

**Review the workflow overview on the image attached (Workflows_MechTreat_v1.jpg)**
- [x]  First acquire the geometry. Note the 10,000sq m size limit
- [x]  Autofill the top elements of the form
- [x]  Keep the form a 3 columns and as condensed as possible
- [x]  The dropdown and booleans MUST be functional and complete
- [x]  The paper file ID inputs I believe are a "add" as required behaviour (not the static 3 columns I have depicted)
- [x]  All booleans default to "no"
- [x]  All fields are mandatory 
- [ ]  create the appropriate table in postgres
- [ ]  load all content into the new table

**Comment by ghost** [comment]
![Workflows_MechTreat_v1.jpg](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/34c36539-bd95-457f-b1df-a9efa88710e2)
