### ISSUE TITLE
Forms: Finalize Terrestrial Plant Chemical Treatment form

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#654]
**Describe the Task**
Ensuring the form content and behaviour is accurate for Creating a Terrestrial Plant Chemical Treatment.

**Acceptance Criteria**
- [ ] Project Management plan should be Pest Management Plan
- [ ] Ensuring validation rules for fields are appropriate as per master variables list
- [ ] Chemical calculation works similar to previous Chemical Treatment form https://invasivesbc.pathfinder.gov.bc.ca/create/chemical 
- [ ] Need option to have more than one species treated
- [ ] The Liquid herbicide list has a recommended application rate (called the "Label"). This value should populate the Application rate field but should still allow the user to over ride the value.
- [ ] Put in PO Review pipeline before closing

![Workflows_ChemTreat_v1](https://user-images.githubusercontent.com/62561887/101389192-e89f1180-3875-11eb-9abb-ab3af2c88c3b.jpg)

**Comment by ghost** [comment]
Acceptance Criteria additions

The Liquid herbicide list has a recommended application rate (called the "Label"). This value should populate the Application rate field but should still allow the user to over ride the value.

**Comment by ghost** [comment]
![Workflows_ChemTreat_v1.jpg](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/38b5716f-6d9c-4a57-94d0-f2af1fcb4290)
