### ISSUE TITLE
Create Terrestrial Animal Observation

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#659]
Description/details:
- [ ]  Create table and fields   
  - [X] **Animal observation table exists in InvasivesBC**
  - [ ] Add to table 'Negative observation' boolean
  - [ ] Add to table 'Sample taken' boolean
  - [ ]  Add to table 'Photo taken' boolean
  - [ ] Species dropdown - populate with **animal invasives CSV**
  - [ ] Agency dropdown - populate with existing plant agency table
  - [ ] Jurisdiction dropdown - populate with existing plant jurisdiction table
  - [ ] Number of individual - will be using preset classes 1 , 2, 3-5, 6-10, 11-50, 50-100, 100+
  - [ ] Behaviour Code - Unknown / Moving / Resting / Deceased
  - [ ]  Life stage dropdown - Unknown, Egg, Neonate, Juvenile, Adult
- [ ] Make API operation
   - [ ] Input Validation Rules
        - all required fields
        - 300 char limit on the 2 comment fields (only standard ascii characters)
 - [ ]  Enforce which roles should be able to use the operation:
    - Details:
       - Data Editor access only
- [ ] Create test

**Comment by ghost** [comment]
The mobile input form ... for use as a guideline in the creation of the web Terrestrial Invasive Animal form


![Animal_Observation.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/cfdd7c93-3852-4cab-9fb5-adbeb6342d67)

**Comment by ghost** [comment]
![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/6726f416-2600-43db-80d5-e44bb3eb5d8a)
