### ISSUE TITLE
Read Terrestrial Animal Observation

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#660]
**Description/details:**
- [ ] Make API operation
- [ ]  Enforce which roles should be able to use the operation:
  - Details:
    - Data Editor access only
- [ ] Create test
- [ ] Displays the content of the observation data just collected
- [ ] sets up the edit/review on the form

**Comment by ghost** [comment]
Review form for the terrestrial animal mobile form

![Animal_review.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/7f655ed0-545f-4c5d-b065-3af57a22214d)
