### ISSUE TITLE
Forms: Finalize Terrestrial Animal Observation form

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#667]
**Describe the Task**
Ensuring the form content and behaviour is accurate for Creating an Terrestrial Animal Observation.

**Acceptance Criteria**
- [X] # of individuals N>0, minimum of 1
- [X] Animal behaviour should be a drop-down

**Comment by ghost** [comment]
The front end look for the Terrestrial Animals mobile form - observation capture

![Animal_Observation.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/05b3ac71-8364-4065-922b-4a3bb584754c)
