### ISSUE TITLE
Forms: Finalize Efficacy Monitoring for Terrestrial Plant Biological Treatment

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#692]
**Describe the Task**
Ensuring the form content and behaviour is accurate for Creating a Efficacy Monitoring for Terrestrial Plant Biological Treatment.

**Acceptance Criteria**
- [ ] @mikeshasko to fill out

Additional Context:
- Monitoring does not require geometry
- Should be tied to the treatment

**Comment by ghost** [comment]
![IAPP_Migration_v6.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/99b762d2-2a26-4c30-84b1-3f921d11d1e1)
