### ISSUE TITLE
Inspect - Re-Formulation of Journey details

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#707]
The current inspect app export to CSV includes a composite set of variables that define the previous and destination water bodies. 

Upwards of 25% of the journey data is coming across as blank. The conservation officers are, however, indicating that they are always adding water bodies where the other 3 toggle items are false.

It is speculated that the conversion of the raw data to the previousJourneyDetails and destinationJourneyDetails is skipping or missing values during the joining of the water bodies to the water body table.

To remedy this, please just re-formulate these 2 fields to just include the concatenation of the 1 or more water body IDs (space delimited) to these fields ie " 3454 9921 1341"

 If the journey details have been defined as other, please include the text string supplied into the appropriate journey detail fields.

Push the code to test and or prod so that a new Watercaft Risk Assessment Report  can be generated or provide Shasko a report file that I can evaluate.

Shasko will take the revised csv report to review if in fact the officers are providing journey details.

Provide Shasko a csv copy of the entire water body table that includes the water body IDs. I will independently join these to the journey data to confirm that original application code was linking to the correct water bodies and determine if/why so many blank results are being created.

**Acceptance Criteria**
- [x] Keep and place the original water body IDs in the  previousJourneyDetails and destinationJourneyDetails fields
- [x] Keep the original join code as we will revisit it
- [x] Provide Shasko a csv copy of the entire water body table that includes the water body IDs

**Additional context**
Current output:

**LakeName         , Country    , Province    , City      , NumberOfDaysOut    , Other    
Nine Bay Lake    , CAN        , BC          , Parson    , 3                  , NA       
Mitten Lake      , CAN        , BC          , Parson    , 2                  , NA       
Bittern Lake     , CAN        , BC          , Parson    , 4                  , NA**       

Required output:
" 3454 9921 1341"

**Comment by micheal-w-wells** [comment]
@mikeshasko as discussed this ask is done (can check out the version with email, the removal of the extra timestamp, and reordering here **https://metabase-8ecbmv-prod.pathfinder.gov.bc.ca/question/18**

I'll make another ticket for the duplicate filtering we chatted about as that is net new.
