### ISSUE TITLE
Unclog lucy-web pipeline

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#709]
**Describe the task**
Since the last team left it seems the pipeline has fallen over, with a number of PR checks failing.

**Acceptance Criteria**
Each of these PR steps needs to pass.  I've tried to add notes that might help.

- [x] Deploy on OpensShift / Build API (pull_request) Failing after 20s — Build API
        _Says it is failing on login.  Curious if system accounts created by former oc project members expire when they lose access?  definitely didn't wipe any system accounts.  Also check out #devops-howto for notes on how the new oc cli getting included in the GH action ubuntu base images can cause issues if the custom action is depending on an older version.  I think between those two things that should sort out any of the openshift PR steps having issues._
- [x] E2E Cypress Test / Cypress e2e test (pull_request) Failing after 11m — Cypress e2e test
       _Haven't sleuthed yet but unless it is an undeterministic test it should be relatively straight forward to scroll back into PR history until we see which one caused this test to fail.  Also possible it depends on another PR step failing here._   
- [x] Test And analysis / Test and Sonar Analysis of API (pull_request) Failing after 10m — Test and Sonar Analysis of API
- [x] Static Deploy on OpensShift / Check Env variables (pull_request) Successful in 1s
- [x] ZAP Baseline Scan / Run Zap Baseline scan (pull_request) Successful in 3m — Run Zap Baseline scan
- [x] Deploy on OpensShift / Build App (pull_request) Failing after 19s — Build App
- [x] Static Deploy on OpensShift / Build API Static (pull_request) Skipped
        _All these skipped ones may be fine but we won't know until the above are sorted, so leaving them here for now._
- [x] Deploy on OpensShift / Clean PR based deployment (pull_request) Skipped
- [x] Static Deploy on OpensShift / Build App Static (pull_request) Skipped
- [x] Deploy on OpensShift / Deploy App and API (pull_request) Skipped
- [x] Static Deploy on OpensShift / Deploy App and API in DEV (pull_request) Skipped
- [x] Static Deploy on OpensShift / Deploy App and API in TEST (pull_request) Skipped
- [ ] Static Deploy on OpensShift / Deploy App and API in PROD (pull_request) Skipped
- [x] Static Deploy on OpensShift / Clean PR based deployment (pull_request) Skipped
- [x] Static Deploy on OpensShift / Clean PR based deployment for Production Env (pull_request) Skipped

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by micheal-w-wells** [comment]
@rstens looks like having a devops guy will come in handy right away, let me know however I can support this ask.

**Comment by rstens** [comment]
It looks like the OpenShift login token has expired. or it was connected to a user id that is no longer part of the project.

It is often underestimated how much babysitting these things need.
Actually, my PR GH actions failed because SECRETS are not being able to be used when submitting a PR from a fork. I guess, the team previously worked directly on the repo without forking it first.

**Comment by rstens** [comment]
Pipeline cleaned all the way up to Test. Reviewed the actions for prod and reviewed the impact the promotion might have on the existing data (It has no impact). For the time being this is working.
