### ISSUE TITLE
Activity page - Mobile InvasivesBC Launch Page

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#713]
As a user of the InvasivesBC Mobile App, once I pass the IDIR/BCeID entry, I am directed to the launch page so that I can proceed on one of six basic field activities.

**Additional Context**
- initial landing page for the app once the splash and login are complete
- a set of  4 buttons for tools/layers/status/activity is activated in the upper right. The buttons DO NOT need to change colour upon being selected (as per illustrated in the mock up)
- a set of 3 buttons for settings/cache/bookmarks is viewable but only the Cache is functional/active (Cache ticket is #785 ). The other 2 can be grayed out
- a set of 4 fields can be set to hold/house some default values that will be auto-filled accordingly upon any activity selected. By default they are blank (un-set). Any time a default element is changed, ONLY the subsequent new records reflect the change NOT on any of the previously captured data.

**Acceptance Criteria**
- [x]  Given I press on the application icon when I enter the app then I am presented with Activities launch page

Work needed to get there:

- [x] Single Sign on
- [x]  push the work to Testflight
- [x] need to pull from the list of jurisdiction and "TNRD?" from the API

**Comment by ghost** [comment]
![Launch.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/92b22d95-3a68-40cd-aee6-cda315d15b85)

**Comment by ghost** [comment]
Noticed from the Sprint review demo ....

Replace "Aquatic" in the GUI with "Animal"

Also - lighten the dark green banner backgrounds - Difficult to see black text.

**Comment by rstens** [comment]
2nd acceptance criteria does not work. The buttons are merely place holders
3rd There is no such "exit" button on the page

**Comment by rstens** [comment]
There should be 3 buttons on the bottom, there are 4 and none of them is active.

**Comment by micheal-w-wells** [comment]
follow up work for Activity Page - mobile

- [x]  Given I am on the landing page when I press any of the above buttons then I am navigated to the related page of the application

**Comment by ZoeSimon** [comment]
> Noticed from the Sprint review demo ....
> 
> Replace "Aquatic" in the GUI with "Animal"
> 
> Also - lighten the dark green banner backgrounds - Difficult to see black text.

@AmirShayegh

**Comment by rstens** [comment]
@mikeshasko Comments were addressed
@micheal-w-wells Added acceptance criterion was addressed
 Cache button is not active, the only active button is the home button
The 4 top fields are currently not retaining entered data, when navigating into an action and then returning, the just entered data has been wiped.

**Comment by micheal-w-wells** [comment]
Thanks @rstens for the thorough testing!  I think the point about it retaining what people chose in the drop down is temporarily delayed until we have the new generic code table endpoint (for populating at least one of those)  up and running in the next week or so.  The overall layout and stuff looks good to me and if its ok with @mikeshasko and @ZoeSimon  the work remaining could be moved to another smaller ticket so we don't keep carrying this one around.

**Comment by ZoeSimon** [comment]
> Thanks @rstens for the thorough testing! I think the point about it retaining what people chose in the drop down is temporarily delayed until we have the new generic code table endpoint (for populating at least one of those) up and running in the next week or so. The overall layout and stuff looks good to me and if its ok with @mikeshasko and @ZoeSimon the work remaining could be moved to another smaller ticket so we don't keep carrying this one around.

Closed and subsequent ticket #789 created to address further work
