### ISSUE TITLE
Investigate Re-using Form Framework

### ISSUE THREAD

**Issue by NickPhura** [bcgov/lucy-web#738]
**Description of Task**

A time-boxed task to investigate the existing Form Framework.
- [x] Determine the feasibility of re-using it for the invasives bc app
- [x] Document any relevant pros and cons of using it.

**Comment by popkinj** [comment]
I believe this is done.
Decided with the team to use NodeJS. Start with a fresh directory in the existing repo and bring in existing code as needed.... Starting fresh yet re-using as much of the previous framework as possible.
