### ISSUE TITLE
UI/UX Revision of workflow diagrams & app research

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#746]
**Describe the task**
- [x] Revision of Mike Shasko's workflow diagram
- [x] Research into the app itself from a user perspective

**Additional context**
- Add any other context about the task here.

**Comment by victorc-bcgov** [comment]
Received latest work-in-progress from @mikeshasko as draw.io document.

The latest desktop version of draw.io desktop can be downloaded from: [http://get.diagrams.net/](http://get.diagrams.net/)

**Comment by ZoeSimon** [comment]
Follow-up UI/UX work will be addressed as needed
