### ISSUE TITLE
Testing Capabilities

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#747]
**Describe the Task**
- [ ] Research on iOS testing in general
- [ ] Pay attention to the difference in the testing capabilities
- [ ] Roland to report back on what approach should be
- [x] Review Mussels & Invasives iOS

**Comment by rstens** [comment]
Mussels has a nice elementary smoke test for the application.
Suggest to do that approach for Invasives as well.

**Comment by rstens** [comment]
I believe this issue is a non issue as the approach taken for Mussels seems the be the way forward.
