### ISSUE TITLE
Activity page - Mobile InvasivesBC Launch Page - Map Background

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#748]
**Describe the Task**
As a user of the InvasivesBC Mobile App, once I pass the IDIR/BCeID entry, I am directed to the launch page so that I can proceed on one of six basic field activities.

**Additional Context**
- initial landing page for the app once the splash and login are complete

**Acceptance Criteria**
- [x]  set up map + buttons for map page

**Comment by rstens** [comment]
I do not see the point of the map background. It is slow, it will most likely not work offline and what value does it add. Sure it works, but.....
