### ISSUE TITLE
Define Geometry Landing Page - Mobile

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#752]
As any mobile data editor user, I want to be directed to the "Define geometry" page once I've selected I want to create an observation or treatment.

**Additional Context**
- 4 selection options are to be presented - each will direct the user to provide a specific geometry
- On the form we have the action button, a small thumbnail image and a description (as noted in the image below
- The type of geometry is to be retained to store in the observation or treatment table
- The "return" icon sends the user back a screen to the activity page
- The 4 upper right tools buttons do not appear (suppressed)
- The 3 bottom buttons should persist but be inactive
- no data table required

**Acceptance Criteria**
- [ ] 4 geom type direct the user to the next screen
- [ ] Shasko to review in Test

**While the invasives plant/animal are focused on 4 primary geometry types, the TAHSIS group may be considering 8-12 additional geometries including lake boundaries, drone tracks, grids etc so please guide your development methods open to being able to extend this functional set.**

**Comment by ghost** [comment]
![Geometry_Define2.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/800d9e3c-2835-4b90-a8ed-3e9f1c2e37c4)

**Comment by ghost** [comment]
![Capture_Point_400.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/fb0e88cf-819d-4491-be17-e8203da2be4a)!

[Capture_Box_400.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/52d9885f-1348-43a4-9932-5d11c08e890b)!

[Capture_Polygon_600.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/f69322a4-afb7-42c0-8386-64895719c503)

![Capture_Waypoint_620.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/dbab8506-bd60-4d18-a565-81363504eb33)

**Comment by ZoeSimon** [comment]
Demo'd in Sprint Review by @anissa-agahchen
