### ISSUE TITLE
TD1 Approach to working with formatted layouts

### ISSUE THREAD

**Issue by anissa-agahchen** [bcgov/lucy-web#753]
### Summary

@micheal-w-wells, @AmirShayegh and @anissa-agahchen met to discuss the layout options.  Need to ensure that option we select allows us to create tests, and not lose sight of the fact that we still need to cache and sync without creating duplicate records in the DB.

### Options
- Option 1 - manual
**pros:**
** do-able
**cons:**
** time consuming

- Option 2 - InputGroup from Mussels-ios
**pros:**
** stable code
** Amir knows it
**cons:**
** doesn't work to generate automated testing

- Option 3 - FormGroup from InvasivesBC-ios
**pros:**
** more mature architecture than InputGroup
** once finished (or understood), can generate automated tests
** improves maintainability
**cons:**
** Code is incomplete
** we are not able to spin up forms with the framework as it is
** this option only has 4 input types, whereas 15 as needed.

### Recommendation
* Use the input groups from Mussels-ios
* ensure tests are done
* ensure caching and syncing are done and testable

**Comment by AmirShayegh** [comment]
The duplicate records is related to the layouts - Its should be handled in the API
