### ISSUE TITLE
Mussel Inspect Export not available

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#755]
**Description of Task**
TBD

**Additional Context**
- Mike Shasko was unable to run the export on 2020-07-27

**Comment by micheal-w-wells** [comment]
Between there being more records and also platform maintenance, the db pod was running slower causing the api to time out.  I upped the CPU req and limit to 1 core to get around it.  Compounding the difficulty in troubleshooting the API did not seem to log anything export related, we used the db logs to show that the query was getting there and that became our hint for the 504.
