### ISSUE TITLE
confirm that the devops pipeline for the ios app is supposed to be on Azure

### ISSUE THREAD

**Issue by anissa-agahchen** [bcgov/lucy-web#771]
the devops pipeline that AMir has access to seems to belong to 'fullboar'.  Is this okay??

**Comment by rstens** [comment]
So at this moment in time this is where it has to be. Jason Leach (I think) has set this up and is the defacto owner. I do not know who fullboar is.

**Comment by anissa-agahchen** [comment]
Sounds good !
