### ISSUE TITLE
Create an app Icon for InvasivesBC 

### ISSUE THREAD

**Issue by anissa-agahchen** [bcgov/lucy-web#772]
**Description of Task**
Create an icon for InvasivesBC Mobile App - For now, we're putting the BCgov icon.

**Additional Context**

**Comment by ZoeSimon** [comment]
@victorchong is there anything else we can call out on this ticket in terms of additional context?

**Comment by victorc-bcgov** [comment]
I have completed research into the technical and identify requirements necessary to create an icon for the InvasivesBC app. Apple's requirements for iOS applications can be found here:

https://developer.apple.com/library/archive/qa/qa1686/_index.html

Note that there are different requirements for iPhone, iPad, and Universal applications. To accommodate these differences, the icon should be created as a vector graphic so that it can be easily scalable to the different dimensions required.

For reference, here are other iOS applications published by the Province of British Columbia. Note that some feature some aspect of the Government's corporate identity such as the BC Mark ("British Columbia" text + sunset logo) or colour palette.

https://apps.apple.com/ca/developer/province-of-british-columbia/id487323275

**Comment by victorc-bcgov** [comment]
Discussed potential designs with @mikeshasko and have landed on a design similar to the Inspect app.

The icon will feature a dary grey silhouette of the inflorescence of the Giant Hogweed (Heracleum mantegazzianum) on a gold radial gradient field. A white circle will be superimposed in the lower right corner, and within this circle will be the Government of British Columbia's "BC Mark", but without the "British Columbia" text.

Note: It is acknowledged that use of the BC Mark in this manner is against corporate guidelines.

https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/policies-procedures-standards/web-content-development-guides/corporate-identity-assets/visid-pdfs/guidelines_thirdpartyuse_bcmarks.pdf

**Comment by ghost** [comment]
As this is invasive plants and animals and fish … might be prudent to supplement the design with fauna

Mike Shasko, MSc MBA
Invasive Species Database & Spatial Data Analyst
Ministry of Forests, Lands, Natural Resource Operations and Rural Development
Operations Division - Range Branch
2975 Jutland, 4th Floor
Victoria, BC  V8T 5J9
Office 778-974-5551

**Comment by victorc-bcgov** [comment]
![iTunesArtwork@1x.png](https://images.zenhubusercontent.com/5f18af5d78dd425eebcf6b97/9d232e7e-19a0-4a5c-aaf6-5e4e3d780c6a)

For your feedback, @mikeshasko.

This design has space on the right side for up to two more silhouettes (albeit at reduced scale), but given that iOS icons are already quite small (76x76 pixels for iPads and 144x144 pixels for iPads with retina display), it may be difficult to make them out with the limited resolution. We can try it out though, if you'd like to squeeze in say a frog and a fish?

**Comment by ZoeSimon** [comment]
> ![iTunesArtwork@1x.png](https://camo.githubusercontent.com/0066f30ca78d4d30db2e43b8a35061d250d5c6b3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566313861663564373864643432356565626366366239372f39643233326537652d313961302d346135632d616166362d356534653364373830633661)
> 
> For your feedback, @mikeshasko.
> 
> This design has space on the right side for up to two more silhouettes (albeit at reduced scale), but given that iOS icons are already quite small (76x76 pixels for iPads and 144x144 pixels for iPads with retina display), it may be difficult to make them out with the limited resolution. We can try it out though, if you'd like to squeeze in say a frog and a fish?

That looks AWESOME @victorchong!!

Could you layer an invasive fish (Yellow Perch for example) **or** an invasive frog (Bullfrog for example) in behind the thistle somehow? Having just one animal might satisfy the Invasive Animal folks without making it look too crowded. @mikeshasko thoughts?

**Comment by ghost** [comment]
Yes .. a fish and/or mussel an/or rabbit

**Comment by victorchong** [comment]
![iTunesArtwork@1x.png](https://images.zenhubusercontent.com/5f18af5d78dd425eebcf6b97/8cd9fd89-6a77-4c85-9772-964f44813346)

I've skewed the thistle and added a perch.

**Comment by victorc-bcgov** [comment]
### **Version 1**
![Invasives 1.png](https://images.zenhubusercontent.com/5f18af5d78dd425eebcf6b97/b1138e65-4887-44ef-9e5d-67fc4269a639)

### **Version 2**
![Invasives 2.png](https://images.zenhubusercontent.com/5f18af5d78dd425eebcf6b97/cfe4c6d2-bcc6-43bd-8f05-f1dec4613592)

### **Version 3**
![Invasives 3.png](https://images.zenhubusercontent.com/5f18af5d78dd425eebcf6b97/d6418a80-9f87-49ad-a905-309f9ed270fb)

**Comment by victorc-bcgov** [comment]
Feedback from sprint review: @mikeshasko to coordinate with Inter-Ministry Invasive Species Working Group (IMISWG).

**Comment by ghost** [comment]
Upon review of the Icon and what the plant folks want to do, they will run with your specs and guidelines that you provided Victor and pass the development on to a designer they have at  MOTI to create and vet an Invasives logo.

They will provide their icon within the next 4 weeks.
