### ISSUE TITLE
Generic Endpoint for Creating records

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#776]
**Describe the task**

Create an endpoint to accept Activities (Observations, Treatments, etc).  The endpoint will populate a number of base columns common to all activities (description, type, dates, and spatial elements), and will have a json column with all the raw data.

A good reason for doing so is we can add new types of data without changing the endpoint.

A rough example of a request to the endpoint to create data is as follows:

```
{
  "ActivityRecordRequest": 
  {
    "ActivityType": "Observation",
    "ActivitySubType": "Invasive Terrestrial Plant",
    "ActivityData": 
    {
      "LocationAndGeometeryData": 
      {
        ...
      },
      "ObservationData": 
      {
        "date": 12-2020-21,
        "other_common_observation_fields": "bla",
        "key activity species name": "bla"
        ...
      },
      "InvasiveTerrestrialPlantObservation":
      {
        "pokyness": 11,
        "smells": "ok"
      }
    }
  }
}
```

Current version of the above spec, supported by the API:

```
{
    "activityType": "",
    "subType": "",
    "date": "",
    "locationAndGeometery": {},
    "data": {}
}
```

**Acceptance Criteria**
- [x] SQL to create the new staging table @popkinj 
  - [x]  location and geometry considerations @popkinj
- [x] Endpoint to insert a new activity  @NickPhura 
  - [x] The swagger.yaml definition for `ActivityPostBody` will need to be updated to match the above JSON spec, if it changes.
  - [x] The SQL for inserting a new activity (found in `activity-queries.ts` will need updating when the initial version of the real staging table is speced out.

**Additional context**
- Current API work, with initial activity endpoint: https://github.com/bcgov/lucy-web/tree/628-create-plant-observation
  - The activity endpoint is touched in these places:
    - `swagger.yaml` -> anything that mentions 'activity'
    - `activity-controller.ts` -> this file and its methods are called when the activity endpoint is called.
      - Any pre/post processing of request/response data should be handled here.
    - `activity.ts` -> simple typescript object to add type support and some processing of the raw request object.
    - `activity-queries.ts` -> contains the WIP SQL for inserting a new activity.

**Comment by micheal-w-wells** [comment]
need to flush out  Spatial considerations for geo/location column(s)

**Comment by micheal-w-wells** [comment]
- [x] staging table @popkinj 
- [ ] activity and location and geometry  @popkinj

**Comment by popkinj** [comment]
Just asking @klefler to have a look at our first crack:

```sql
-- ### Creating Table: activity_incoming_data ### --
  

CREATE TABLE activity_incoming_data ();
COMMENT ON TABLE activity_incoming_data IS 'Store all incoming data if valid. All mandatory columns must be preset (type & geometry). This is a staging area for further propagation and acts as a source of truth for all field data.';

ALTER TABLE activity_incoming_data ADD COLUMN activity_incoming_data_id SERIAL PRIMARY KEY;
COMMENT ON COLUMN activity_incoming_data.activity_incoming_data_id IS 'Auto generated primary key';

ALTER TABLE activity_incoming_data ADD COLUMN activity_id VARCHAR(20) NOT NULL CHECK (record_id > 0);
COMMENT ON COLUMN activity_incoming_data.activity_id IS 'Unique record number. Can occur multiple times with record updates.';

ALTER TABLE activity_incoming_data ADD COLUMN version INTEGER NULL;
COMMENT ON COLUMN activity_incoming_data.record_id IS 'Indicative of the version for each unique record. Calculated server side.';

ALTER TABLE activity_incoming_data ADD COLUMN type VARCHAR(20) NULL;
COMMENT ON COLUMN activity_incoming_data.type IS 'Type of record';
CREATE index type_idx on activity_incoming_data (type);

ALTER TABLE activity_incoming_data ADD COLUMN sub_type VARCHAR(20) NULL;
COMMENT ON COLUMN activity_incoming_data.sub_type IS 'Sub Type of record';
CREATE index sub_type_idx on activity_incoming_data (sub_type);

ALTER TABLE activity_incoming_data ADD COLUMN received_timestamp timestamp NOT NULL DEFAULT NOW();
COMMENT ON COLUMN activity_incoming_data.received_timestamp IS 'The date and time data was received and inserted into the database.';

ALTER TABLE activity_incoming_data ADD COLUMN geom geometry(GeometryCollection,3005);
COMMENT ON COLUMN activity_incoming_data.geom IS 'Geometry collection in Albers projection.';
CREATE index activity_incoming_data_gist on activity_incoming_data using gist ("geom");

ALTER TABLE activity_incoming_data ADD COLUMN activity_payload JSONB;
COMMENT ON COLUMN activity_incoming_data.activity_payload IS 'Raw data upload in compressed JSON format.';
```

**Comment by klefler** [comment]
Hi @popkinj, just took a quick look at the script. Some comments:

For the table comment, could you please add some more definition for "activity". Such as, "Stores all incoming validated data for activities (i.e. observation, treatment, monitoring)."

activity_id - the column comment might need a bit more clarification to define the activity_id is the unique id of the activity. i.e. "Unique identifier for the associated activity record"?

type column - should be renamed to activity_type. The column comment should include example of the activity type. Question: Should the type be managed in a separate table and referenced through this column as a foreign key?

sub_type - similar question as above... the column should be renamed activity_sub_type and the column comment should include example of sub types.

Should consider adding the 4 audit columns that are standard with database tables (created_at, updated_at, created_by_user_id, updated_by_user_id)... this may impact the received_timestamp?

Let me know if you want to chat. Thanks!

**Comment by micheal-w-wells** [comment]
Gonna break off some remaining sub tasks for this, but there is an endpoint that can be hit now.

What was done here:

- [x] Make Nick's API work with Jamie's staging table
- [x] Make generic endpoint and base set of activity fields to be part of request
- [x] Include base set of location fields common to all activity types.
- [x] Add test CURL command for testing
- [x] Add `knex` to manage migrations moving forward (including Jamie's changes)
- [x] Add shell script to sync .env variables between old API docker container and new local API run time.

**Comment by micheal-w-wells** [comment]
Make swagger schema validation present a more readable error (for all new endpoints).

Right now the stack dump that is presented if the schema of the request is invalid does not give the user hints as to what the problem is.  This task is to make that error more clear for the API consumer as to what field(s) are the problem.

- [ ] if i send a bad request it will give me a readable error.

**Comment by micheal-w-wells** [comment]
Set up location and geometry validation on API

- [ ] Use swagger and/or PostGIS to validate geometries sent to API.
- [ ] Errors are human readable.

**Comment by micheal-w-wells** [comment]
Closing this one so we are just bringing the smaller sub tasks into next sprint.
