### ISSUE TITLE
Get openshift set up and deployment done for activity endpoint 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#778]
**Describe the task**
@NickPhura help me fill this out

Some general things to check, that may be helpful when developing this:
- Check what the current api builld/deployment configs do, in particular around any npm commands they run, or any dist folders they reference.
  - Check the api/api_sources/package.json for related commands and possibly copy them over into the new api's package.json.
  - Compare the tsconfig.json files from both apis for possible changes related to building the app into the form it needs to run in OpenShift.
- Search api/api-mobile for `process.env` to see the currently used environment variables, some of which may need to be set as OpenShift variables/secrets.

**Acceptance Criteria**
- [x] endpoint works in openshift
- [x] @rstens helps with overview of pipeline

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by rstens** [comment]
[Explanation of PipeLine Presentation](https://teams.microsoft.com/l/file/62F67F46-0923-4D75-A8AF-B42DD7F8E53B?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=pptx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F02125%2FShared%20Documents%2FDevOps%2FDevOps%20Overview%20Invasives.pptx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F02125&serviceName=teams&threadId=19:863a4db190cd4aeda384381d263450aa@thread.tacv2&groupId=b48794d7-3e9b-41c0-ab7e-618bf89c95b3)
