### ISSUE TITLE
Main API boilerplate and auth working in docker

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#779]
**Describe the task**
Use existing docker setup from `./api` to kickstart docker setup for `./api-mobile`

**Acceptance Criteria**
- [x] api-mobile runs in Docker
- [x] add api-mobile to the existing makefiles/scripts so that `make run-local` (and similar) also run the api-mobile docker
- [ ] PR

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by NickPhura** [comment]
In hindsight, this was more like a 3 or 5.  Was 3 full days of work.

**Comment by ZoeSimon** [comment]
> In hindsight, this was more like a 3 or 5. Was 3 full days of work.

Let me just update that estimate for ya
