### ISSUE TITLE
need to flush out  Spatial considerations for geo/location column(s)

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#780]
**Describe the task**
need to flush out  Spatial considerations for geo/location column(s) for create activity endpoint @popkinj to add details here

**Additional context**
- Add any other context about the task here.
- Or here

_Originally posted by @micheal-w-wells in https://github.com/bcgov/lucy-web/issues/776#issuecomment-670040178_

**Comment by popkinj** [comment]
Using [turf](https://turfjs.org/) to validate and possibly manipulate data.

**Comment by popkinj** [comment]
Thinking more about this. It may work to use PostGIS to do the validation.

**Comment by micheal-w-wells** [comment]
Like a 'before insert' trigger on the staging table @popkinj ?

**Comment by micheal-w-wells** [comment]
(that's where I've put db based input validation before, throw an error in that trigger)

**Comment by popkinj** [comment]
Yeah... that would work.

**Comment by popkinj** [comment]
Hmmmm... Although way want Node in on the action somehow. Just so we can respond accordingly.

**Comment by micheal-w-wells** [comment]
I think as long as those errors get passed back up to node and the API caller in a readable way we're set

**Comment by popkinj** [comment]
Think this should do the trick:
```sql
ALTER TABLE activity_incoming_data
ADD COLUMN geom geometry(GeometryCollection,3005)
CHECK (st_isValid(geom));
```

**Comment by popkinj** [comment]
In order for PostGIS to work you have to have the `public` schema, as well as the `invasivesbc` schema, in your search path.
```sql
set search_path=invasivesbc,public;
```
