### ISSUE TITLE
Spatial join requirements for activities

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#797]
**Data Porting for Overlay requirements**
Extracting spatial layers from the _Land Resource Data Warehouse (LRDW)_ to be inserted into the the _InvasivesBC_ database. This a requirement for performing spatial joins and filling in data for various Activity columns. These will not be definitive versions of the data and may require update in the future. 

**Private shapefiles** (not in LRDW) ... might have to be added into PostGIS to use internally.
- [ ] RISO - Regional Invasives Species Organization (Private shape file layer Shasko maintains)
- [ ] IPMA - Invasive Plant Managemnt Area (Private shape file layer Shasko maintains - nests with RISO's) - Pending in progress updates.

**Extract Spatial Layer from LRDW**
All schemas shall remain the same as their source.
- [x] BEC ZONE
- [x] Ownership
- [x] Regional District
- [x] FLNRO Distrtict
- [x] MOTI District
- [x] UTM Zones
- [x] DEM (I may have a copy of this from another project)

**Inserting layers into InvasivesBC**
All tables should be commented regarding source. A link to the appropriate record in the [Data BC Catalogue](https://catalogue.data.gov.bc.ca/dataset?q=&sort=record_publish_date+desc%2C+metadata_modified+desc) should be provided.
- [x] BEC ZONE
- [x] Ownership
- [x] Regional District
- [x] FLNRO Distrtict
- [x] MOTI District
- [x] UTM Zones
- [ ] ~~DEM (Will require the raster plugin for PostGIS)~~ Too much disk space

**Comment by popkinj** [comment]
Hey @mikeshasko 
Can you tell me what the RISO and IPMA datasets are?

Thanks.

**Comment by ghost** [comment]
@popkinj   I've revised the criteria  as such

**Comment by popkinj** [comment]
Hey @mikeshasko 
For ownership. Are you ok with just **Crown** vs **Private**?

**Comment by popkinj** [comment]
Didn't have a copy of the Provincial DEM... But had all the individual Esri Asci files. Along with a recipe I used previously.
```bash
gdal_merge.py -o dem.tif -co "COMPRESS=LZW" -co "BIGTIFF=YES" $(ls *.asc)
gdalwarp -s_srs 'epsg:3005' -t_srs 'epsg:4326' -co "COMPRESS=LZW" -co "BIGTIFF=YES" dem.tif dem_geo.tif
raster2pgsql -s 'epsg:4326' -t 25x25 -I -Y dem_geo.tif invasivesbc.dem > dem.sql
```

**Comment by ghost** [comment]
I also have a BC Albers DEM that extends beyond the provincial boundary that would support migrations in/out of the province.

35m res, 4gb GeoTiff



Mike Shasko, MSc MBA
Invasive Species Database & Spatial Data Analyst
Ministry of Forests, Lands, Natural Resource Operations and Rural Development
Operations Division - Range Branch
2975 Jutland, 4th Floor
Victoria, BC  V8T 5J9
Office 778-974-5551
