### ISSUE TITLE
Activity Launch Page typos

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#804]
**Describe the Bug**
From issue #713 typos in the green activity bars persist  (Mobile release 6.03 and 6.08)

Should say ...

Plant -  Invasive Terrestrial / Aquatic

Animal-  Invasive Terrestrial / Aquatic

![image.png](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/7c2552a8-3e39-41dc-8f9c-8fb26e2da8df)

Current error:

![IMG_0078.PNG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/b576ecb4-b466-4136-8dc6-248c811f17ba)

- [ ] @mikeshasko to test and close upon completion

**Comment by ZoeSimon** [comment]
@mikeshasko Can you include a screenshot of what is says currently in the app so it's super clear? Thanks! :)

**Comment by ZoeSimon** [comment]
@anissa-agahchen said that she would include these changes in the next build. She will let @mikeshasko know when it's available in Testflight.
