### ISSUE TITLE
INFO Ticket: Decide what elements will be cached offline

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#811]
**Describe the Task**
@mikeshasko to list out everything a user would cache other than the data they are making themselves.

**Acceptance Criteria**
- [ ] cache page to allow for creating 1 cache environment 
- [ ] consider possibly 3 cache areas (optional)
- [ ] cache page to provide total space available field
- [ ] cache page to provide total used space available field
- [ ] allow user to define an area or use the current map area as the cache frame 
- [ ] allow the user to erase the local cache
- [ ] default layers (see mock up)
    - Default Layers that were left off the mock-up but need to be added:
       - [ ] First Nations Reserves
       - [ ] Imagery (ESRI)
- [ ] optional layers (see mock up)
    - Optional Layers that were left off the mock-up but need to be added:
       - [ ] WMUs
       - [ ] Freshwater atlas

@robinmunro to add additional layers and items to the comments

BioHub/Invasive Final List:

- [ ]  Legacy IAPP sites / Surveys / Treatments
- [ ]  Regional Districts and Municipalities
- [ ]  Well sites
- [ ]  Natural Resource Districts
- [ ] MOTI Regions / Districts
- [ ]  BEC layers
- [ ]  RISO boundaries
- [ ]  IPMA (invasive plant management areas)
- [ ]  Wildlife Management Units
- [ ]  Legal and Proposed GAR Designation
- [ ]  Ungulate Winter Range
- [ ]  Fisheries Sensitive Watershed
- [ ]  Wildlife Habitat Areas
- [ ]  Old Growth Management Areas
- [ ]  Freshwater Atlas (FWA)
- [ ]  Streams
- [ ]  Lakes, wetlands, manmade waterbodies
- [ ]  Major rivers
- [ ]  Obstructions
- [ ]  Ownership Layers
- [ ]  Provincial Parks
- [ ]  Ecological Reserves
- [ ]  Protected Areas
- [ ]  Recreation Areas
- [ ]  Conservation Areas
- [ ]  FN Reserves
- [ ]  National Parks

**Comment by ghost** [comment]
![811_Mockup.JPG](https://images.zenhubusercontent.com/5e6f9a0410bdde585c919946/277b2451-bd97-48c0-9ada-f6fc3c6b9828)

**Comment by robinmunro** [comment]
•	Management Units
•	Legal and Proposed GAR Designation
         o	Ungulate Winter Range
         o	Fisheries Sensitive Watershed
         o	Wildlife Habitat Areas
•	Old Growth Management Areas
•	Freshwater Atlas (FWA)
         o	Streams
         o	Lakes, wetlands, manmade waterbodies
         o	Major rivers
         o	Obstructions
•	Ownership Layers
         o	Provincial Parks, EcoReserves etc
                    	Provincial Parks
                    	Ecological Reserves
                    	Protected Areas
                    	Recreation Areas
                    	Conservation Areas
         o	FN Reserves
         o	National Parks
         o	Municipalities
