### ISSUE TITLE
Decide how API should work (for photo endpoint)

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#840]
**Describe the task**
Decide how API should work (for photo endpoint).

**Acceptance Criteria**
- [ ] Reach out to Gary Wong to find out what steps are
- [x] Decide what InvasivesBC database and API need to do and what information needs to go there and on s3.

**Comment by NickPhura** [comment]
In regards to the initial setup, my last project went through the process of setting up the government object store, and using the s3 api, etc.  So I have code I can steal from to jump start us. Also, I created a free AWS account and created a bucket, so I was planning on testing with that in the short term. Should be relatively straight forward, I think, to at least get something simple set up.
