### ISSUE TITLE
Implement photo endpoint & s3 integration Part 1 (Post)

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#841]
**Describe the task**
Implement photo endpoint & s3 integration (post). Dependent on #840.

**Acceptance Criteria**
- [x] photo can be uploaded to s3
- [x] reference to photo in s3 lands in InvasivesBC database

**Comment by NickPhura** [comment]
Getting started on initial basic setup, re: https://github.com/bcgov/lucy-web/issues/840#issuecomment-682166452
