### ISSUE TITLE
backup container

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#849]
**Describe the task**
set up a backup container for other range project that is also using psql

Not sure if you need all the namespaces or not @rstens but made you an admin for now in all of them anyway:
https://console.pathfinder.gov.bc.ca:8443/console/project/range-myra-tools/overview
https://console.pathfinder.gov.bc.ca:8443/console/project/range-myra-dev/overview
https://console.pathfinder.gov.bc.ca:8443/console/project/range-myra-test/overview
https://console.pathfinder.gov.bc.ca:8443/console/project/range-myra-prod/overview

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by rstens** [comment]
Installed and tested backup containers for: dev,test and prod
Dev/Test have a 1GB container, prod has a 5GB one.
