### ISSUE TITLE
Change github actions' "checkout action" from v1 to v2

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#878]
**Describe the task**
There's a bug in v1 where a PR that gets merged prior to all checks being done will cause the checkout action to fail.  Fixed in v2 according to the Github guy I emailed (thinking it might have been a service disruption at the time).

**Acceptance Criteria**
- [x] change from v1 to v2
- [x] pipeline still works
- [x] merging before PR actions done doesn't cause some to fail

**Comment by rstens** [comment]
Is fixed.
