### ISSUE TITLE
Come up with plan for how to cache layers on mobile device

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#879]
**Describe the task**
Come up with plan for how to cache layers on mobile device. Subsequent ticket is #784

**Acceptance Criteria**
- [ ] Plan for how to get layers onto the device (API)
- [ ] Plan for storage medium on device (GRDB or ?)

**Comment by micheal-w-wells** [comment]
something to check out https://rxdb.info/rx-schema.html#attachments

**Comment by popkinj** [comment]
This plugin look promising: https://github.com/allartk/leaflet.offline

**Comment by ZoeSimon** [comment]
Duplicate of ticket #46
