### ISSUE TITLE
Inspect Metabase table addition

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#894]
With the SQL code to create the inspect compilation table we wish to add an additional column to the output, specifically "general comments".

Mike S. needs some help from Mike W with regards to this change - making sure I've address the correct SQL version.

**Comment by micheal-w-wells** [comment]
I looked at the last one i edited, Export 3.0, and it looks like you've added it there and did it correctly.  I can see why you thought you might not have though as there's really no data for that column.

I ran this and got 0 results:

`select count(*) from high_risk_assessment where general_comments not in ('None', null)`

Either this isn't the column we are looking for, they aren't using it, or (worst case) it's the right column and they are using it but the iOS device and/or API isn't populating it.

**Comment by micheal-w-wells** [comment]
- [ ] mike to explore a couple versions of app as this one seems to be blank
