### ISSUE TITLE
Make Ionic Android pipeline

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#900]
**Describe the task**
@rstens I"ll let you fill this one in, and the apple pipeline will be a separate (later) issue you can work with platform services with.

**Acceptance Criteria**
- [x] produces a binary that will run on an android device and ideally a link to it

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by rstens** [comment]
The resulting debug-apk is created as an artifact in the GH Action and can be downloaded after the run.
