### ISSUE TITLE
GH repo for Ionic app

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/lucy-web#918]
Tasks:

- [x] Create invasivesbc repo: https://github.com/bcgov/invasivesbc
- [x] Set Up basic Structure
- [x] Give access to team
- [x] Review key structure with team
- [x] Merge App and API Code (from ionic and mobile API) (@NickPhura )
- [x] Decide on Branches (dev (default), test, master) (Roland)
- [x] Set up secrets for pipelines (Roland)
- [x] Create documentation for starting the app (Roland/Nick)
- [x] Connect Repo to SonarCloud/CodeCov (Roland)

**Comment by rstens** [comment]
SonarCloud and CodeCov are now activated.
