### ISSUE TITLE
Inspect data is not populating the InvasivesBC web site

### ISSUE THREAD

**Issue by ghost** [bcgov/lucy-web#926]
Typically when I entry the invasivesBC prod site I get an update on the Inspect records and the option to export them to CSV.
This can sometimes take up to a minute to refresh but now even after 5 minutes there is nothing.
I can obtain the data via Metabase but other users (Martina and Aaron) still pull it weekly from the web site.

Can we confirm that the inspect data is still being dumped here and that something in the pipeline isn't broken.

I require this table to confirm issue #894

**Comment by micheal-w-wells** [comment]
The quick and dirty fix was to get the right comment column as part of the metabase export.  That solves it for you.

Any thoughts about getting access to run an export for Martina / Aaron?  General fixes for metabase exports are gonna be a lot cheaper/faster than in the web app.

I'll have a peek now and see if I can spot what the big issue is but not sure how involved a fix will be.

**Comment by micheal-w-wells** [comment]
data is there, mike can see in report, report now emailed automatically weekly to Martina / Aaron.
