### ISSUE TITLE
Create Local build scripts for Web App/Mobile

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/lucy-web#928]
**Describe the task**
@NickPhura 

**Acceptance Criteria**
- [x] Add docker files for local docker build/run

**Additional context**
- [x] Refer to ticket #63

**Comment by NickPhura** [comment]
Currently blocked by the OpenShift storage issues.  Tried this morning, pvcs are still disabled.

**Comment by NickPhura** [comment]
Storage seems to be re-enabled, so unblocked!
